### ISSUE TITLE
Methods utility

### ISSUE THREAD

**Issue by andreasvirkus** [eddyerburgh/avoriaz#1]
Firstly, thanks for a small and useful utility wrapper for Vue.js' testing purposes!

I think there's a small bug in Wrapper.js' methods() function? It references `$options.method` instead of `$options.methods`. When I changed it under dist/Wrapper.js it started working for me. Could you double-check? I could make a PR. 

BR,
Andreas

**Comment by eddyerburgh** [comment]
Yep that's definitely a bug. There must be a problem with the tests too, since they're all passing.

If you could make a PR with a fix and a test that would be great, if you don't have time then I can do it later :smile:

**Comment by andreasvirkus** [comment]
Created PR #2

**Comment by andreasvirkus** [comment]
Similarly to `.methods()`, `.find()` also doesn't seem to work for me... `.contains()` and `.is()` work however.

**Comment by eddyerburgh** [comment]
Thanks for the PR. Could you create a new issue for .find with more details? That's tested fairly extensively so the solution will be more complicated.
