### ISSUE TITLE
Getting the value of an input element

### ISSUE THREAD

**Issue by M-Zuber** [eddyerburgh/avoriaz#107]
Given an element like so `<input type="text" v-model="value">`

How can I access the value of the element?

**Comment by M-Zuber** [comment]
I made the changes to make this work, is it something you would be interested in a PR for?

**Comment by eddyerburgh** [comment]
Yeah, what were the changes?

**Comment by M-Zuber** [comment]
pretty much this:
```
  value() {
    if (!this.element.value) return false;
    return this.element.value;
```

**Comment by M-Zuber** [comment]
The pr is here #114

**Comment by eddyerburgh** [comment]
This is now live in 3.3.0 

Thanks for the PR 🙂
