### ISSUE TITLE
Running docs locally

### ISSUE THREAD

**Issue by M-Zuber** [eddyerburgh/avoriaz#108]
(This is on windows if that makes a difference)
After running `npm run docs:build` I attempted to run `npm run docs:watch`, but it fails with the following message:
`Error: Couldn't locate plugins "edit-link, prism, github, theme-vuejs", Run 'gitbook install' to install plugins from registry.`
but `gitbook install` tells me there is nothing to install

As an aside: are contributors expected to update the docs themselves, or is that all done by you when publishing?

**Comment by eddyerburgh** [comment]
Hi, sorry for the delayed response. I've been on vacation 🏖

`docs:watch` should be fixed with cc04f789fac58b416746e49a8137f1c5d257bb4d

Contributors are not expected to publish the docs, but they are expected to update the docs with information on new/ changed features.

**Comment by M-Zuber** [comment]
👍 Thanks for the fix and update

Hope your vacation is going well
