### ISSUE TITLE
trigger('click') does not fire the click

### ISSUE THREAD

**Issue by bilougit** [eddyerburgh/avoriaz#111]
I'm testing a **new custom component** which I created.
When clicking on `arrow-img`, the class `active-menu` should be moved from the first `li` to the second `li`. 

My tests after `trigger('click')` suggest that nothing has changed as if the `arrow-img` hasn't been clicked.

```javascript
expect(firstLi[0].element.className).to.equal('active-menu');
expect(secondLi[0].element.className).to.equal('');

arrowImg[0].trigger('click');


// These tests do not pass
expect(firstLi[0].element.className).to.equal('');
expect(secondLi[0].element.className).to.equal('active-menu');
```

And here is my component js

```javascript
import jQuery from 'jquery';
window.$ = window.jQuery = jQuery;

// This contains jquery DOM manipulation
import {runjQuery} from './js/home';

require('nmodules/bootstrap-sass/assets/javascripts/bootstrap/collapse.js');

export default {
    created() {
        runjQuery(jQuery);
    },
};   
```

As you can see, my component DOM is fully manipulated by `jQuery`.

Is this the reason `trigger('click')` has no effect on my component?
How do I fix it?

**Comment by eddyerburgh** [comment]
Hi, the component needs to have a render function that renders something for avoriaz to test the DOM. Alternatively, you can simply call mount with the option `attatchToDocument: true` and use a DOM testing library for your assertions.

Something like this:
```js
mount(Component, {
  attachToDocument: true
})

$('.arrow').click()
expect($('li:first-of-type').hasClass('')).to.equal(true)
```
