### ISSUE TITLE
Mocking method on component (using Jest)

### ISSUE THREAD

**Issue by lmiller1990** [eddyerburgh/avoriaz#116]
Hi,

I am trying out avoriaz with Jest. So far this library is great, thanks a lot. 

I want to mock a method that makes an api request.

My code looks something like

### SomeComponent.vue
```
<template>
  <form>
    <button type="button" id="my-button" @click="save">Btn</button>
  </form>
</template>

<script>
  export default {
    methods: {
      save () {
        // stuff
      }
    }
  }
</script>
```

### Test
```
import { shallow } from 'avoriaz'
import Vue from 'vue'
import SomeComponent from './SomeComponent.vue

describe('mocks a method', () => {
  it('mocks it', () => {
    const wrapper = shallow(SomeComponent)
    // I want to mock the `save` method with `jest.fn()` - how do I do that?
    /* I have tried...    
    wrapper.methods().save == jest.fn()
    wrapper.vm.save = jest.fn()
    */
 
    // rest of the test
    wrapper.find('#my-button')[0].trigger('click')
    expect(/* mock to have been called */)
  }
}
```

I saw some examples around using sinon, but the same should work for jest. So I would like to know how I can mock a function - I was struggling to find an example. I did see one other example where a mocked function was passed using `propsData`? Is that what I should be doing?

**Comment by eddyerburgh** [comment]
You were nearly there:

```js
it('mocks it', () => {
    const wrapper = shallow(SomeComponent)
    const saveMock = jest.fn()
    wrapper.vm.save = saveMock
    wrapper.update()

    wrapper.find('#my-button')[0].trigger('click')
    expect(saveMock.mock.calls.length).toBe(1)
})
```

I'm going to add a setMethod method at some point to make this easier to understand.

**Comment by lmiller1990** [comment]
So I had to call `update`! I didn't realise this would also update the setting of new methods.

Can I make a PR with this information in the docs somewhere? Mocking a function seems like a common use case but from I can see it isn't mentioned in the docs.

Maybe a section on mocking under guides? I think this library is a game change for a lot of people building Vue apps, and more guides/examples would help more people pick it up.

Thanks for the quick feedback! And for this fantastic library. If you want to talk more about updating/new guides I'm happy to help out.

**Comment by eddyerburgh** [comment]
Yes I'd welcome a PR 😄 

I think the best solution would be to add a setMethods method, similar to vue-test-utils - https://github.com/vuejs/vue-test-utils/blob/dev/src/wrappers/wrapper.js#L260

If you are up for it, you could make a PR adding setMethods, as well as a mocking guide in the docs

**Comment by eddyerburgh** [comment]
vue-test-utils has a slightly different API. You can see a full list here - https://github.com/vuejs/vue-test-utils/tree/master/docs/en/api/wrapper

`find` also behaves differently, it returns the first matching item. vue-test-utils has a `findAll` method that returns an array like object.

They won't merge, but I will focus most of my effort on vue-test-utils.

There is documentation, but it hasn't been linked to a gitbooks yet (so there's no website). You can see the English docs in the repo here - https://github.com/vuejs/vue-test-utils/tree/master/docs/en

**Comment by lmiller1990** [comment]
Thanks for the link to the docs.

I made a PR. I would like to improve the docs too, for this and for other areas, maybe that can come in another PR/issue?

Also, should I start to focus more on the official vue-test-utils, or there is need for this project alongside the official tools?

**Comment by eddyerburgh** [comment]
Thanks 👍 

vue-test-utils is the official solution - a guide on stubbing methods would be greatly appreciated. It would be useful to add a guide to avoriaz too, but vue-test-utils is definitely the priority.

**Comment by eddyerburgh** [comment]
`setMethods` has been merged and is now live in v3.4.0 👏

**Comment by lmiller1990** [comment]
Great! I'll close the issue. I will be looking to do some writeups of how to mock/stub methods, and hopefully add a guide about it too in the future (maybe here, or the official test-utils repo, or both).

Thanks again for the quick reviews and responses and great lib!

**Comment by preetiksingh** [comment]
@eddyerburgh How do I mock an api call ?

<template>
 <div>
  <p>{{msg}}</p>
  <button id="toggle-message" @click="toggleMessage">
   Change message
  </button>
  <button id="users" @click="getData">
   Get Users
  </button>
   {{users}}
 </div>
</template>

<script>
  import axios from 'axios'

  export default {
    name: 'message-toggle',
    data: function () {
      return {
        msg: 'default message',
        users: []
      }
    },
    methods: {
      toggleMessage () {
        this.msg = this.msg === 'message' ? 'toggled message' : 'message'
      },
      getData () {
        var vm = this
        axios.get('https://jsonplaceholder.typicode.com/users')
        .then(function (response) {
          vm.users = response.data
          console.log('response.data', response)
        })
      }
    }
  }
</script>



//Basically this method 👍 
getData () {
        var vm = this
        axios.get('https://jsonplaceholder.typicode.com/users')
        .then(function (response) {
          vm.users = response.data
          console.log('response.data', response)
        })
      }

**Comment by lmiller1990** [comment]
@preetiksingh  read this https://vue-test-utils.vuejs.org/en/guides/testing-async-components.html

**Comment by preetiksingh** [comment]
Hi @lmiller1990 thanks for the link. I am trying to implement it but not sure where to put this code 

"The implementation of the axios mock looks like this:

export default {
  get: () => new Promise(resolve => {
    resolve({ data: 'value' })
  })
}
"

And currently my component looks like this 

//Foo.vue

<template>
  <button @click="fetchResults" />
</template>

<script>
  import axios from 'axios'

  export default {
    data () {
      return {
        value: null
      }
    },

    methods: {
      async fetchResults () {
        const response = await axios.get('https://jsonplaceholder.typicode.com/users')
        this.value = response
      }
    }
  }
</script>
And my test spec file is this:

TestApi.spec.js

import { mount } from 'vue-test-utils'
import flushPromises from 'flush-promises'
import Foo from '@/components/Foo.vue'
jest.mock('axios')

describe('Foo', () => {
  it('fetches async when a button is clicked', async () => {
    const wrapper = mount(Foo)
    console.log("check",wrapper )
    wrapper.find('button').trigger('click')
    await flushPromises()
    expect(wrapper.vm.value).toBe('value')
  })
})


Can you please help me with the implementation where I am going wrong:
My console says this:

 ● Foo › fetches async when a button is clicked

    expect(received).toBe(expected) // Object.is equality
    
    Expected value to be:
      "value"
    Received:
      undefined
    
    Difference:
    
      Comparing two different types of values. Expected string but received undefined.

      10 |     wrapper.find('button').trigger('click')
      11 |     await flushPromises()
    > 12 |     expect(wrapper.vm.value).toBe('value')
      13 |   })
      14 | })
      15 | 


Thanks and Regards,
Preeti

**Comment by lmiller1990** [comment]
Hey @preetiksingh ,

Can you format your code using three ` marks? It will make the code snippet easier to read. Example:

```
``` <- put three of these above and below
function() {
  console.log('this is formatted')
}
```

function() {
  console.log('this is formatted')
}

The first is much easier to read.

Here is your code formatted. Btw, I thin you forgot the `<template>` part?

```html
<script> 
  import axios from 'axios' 
  export default { 
    data () { 
      return { value: null } 
    }, 
    
    methods: { 
      async fetchResults () { 
        const response = await axios.get('https://jsonplaceholder.typicode.com/users') 
        this.value = response 
      } 
   } 
} 
</script>
```

```js
import { mount } from 'vue-test-utils'
import flushPromises from 'flush-promises'
import Foo from '@/components/Foo.vue'
jest.mock('axios')

describe('Foo', () => {
  it('fetches async when a button is clicked', async () => {
    const wrapper = mount(Foo)
    console.log("check",wrapper )
    wrapper.find('button').trigger('click')
    await flushPromises()
    expect(wrapper.vm.value).toBe('value')
    })
})
```

Second, since you are using jest and called `jest.mock('axios')`, you need to provide a mock (something for just to use instead of the real `axios`. Here is a quick one to get you started:


```
let data = {}

export function setMockResponse(mockData) {
  data = mockData
}

export default {
  get: url => {
    return new Promise(resolve => resolve(data))
  }
}
```

That goes in `__mocks__`, which should be on the same level as `node_modules`.

Now you can use the the mock like this:


```
import { mount } from 'vue-test-utils'
import flushPromises from 'flush-promises'
import Foo from '@/components/Foo.vue'
jest.mock('axios') // you shouldn't need this - just does automatically for node_modules
import { getMockResponse } from "axios" // jest will use the file in __mocks__ automatically

describe('Foo', () => {
  it('fetches async when a button is clicked', async () => {
    setMockResponse("value") // set the response

    const wrapper = mount(Foo)
    console.log("check",wrapper )
    wrapper.find('button').trigger('click')
    await flushPromises()
    expect(wrapper.vm.value).toBe('value')
    })
})
```

Something like that - I didn't test so I might have made a mistake. Try that and let me know what happens.

**Comment by preetiksingh** [comment]
Hi @lmiller1990. Thanks for the help and Can you tell me how do I mock a function which do not have an api call.

For example I have a method in one of my components as : 
```
whenFiltered (filteredItems) {
      this.totalRows = filteredItems.length
      this.currentPage = 1
    }
```
This filtered items we are getting from bootstrap-vue.common.js under node modules. I get an array of objects which I am displaying as multiple rows. What are the possible tests I can do here.

Can you give a code snippet for this.

**Comment by lmiller1990** [comment]
Wait so you want to test `whenFiltered`?

1. does it set `totalRows`?
2. does it set `currentPage`?

```js
it('works', () => {
  let localThis = { totalRows: 0, currentPage: 1}
  whenFiltered.call(localThis, new Array(2))
  
  expect(localThis.totalRows).toBe(2)
  expect(localThis.currentPage).toBe(1)
}
```

You use https://github.com/vuejs/vue-test-utils instead of avoriaz.

Also, I think you should ask this on stackoverflow using `vue-test-utils`, or `testing`, `tdd`, `javascript`  tags. More people can respond there. This repo is for bugs or problems with avoriaz. Thanks.

**Comment by preetiksingh** [comment]
Hey, Thanks @Imiller1990

**Comment by ekramulmostafa** [comment]
@lmiller1990 and @eddyerburgh ,
Guys can you please help me out with a simple page unit testing. I'm noob in vue unit testing. I need to check the functions return values and also the rendered ContentListBlock printed content if possible.

ContentList.vue page
---------------------------------------------------
```
<template>
    <section class="total-content-list">
        <h1>Content list (Vue JS)</h1>
        <ContentListBlock v-for="item in contentLists" :key="item.id"
                          :bongoId="item.bongoId"
                          :contentName="item.title"
        ></ContentListBlock>
    </section>
</template>

<script>
    import axios from 'axios'
    import ContentListBlock from '@/components/ContentListBlock'

    export default {
        name: 'ContentList',

        data() {
            return{
                baseURL: 'BASE URL',
                token: '',
                contentLists: []
            }
        },
        components: { ContentListBlock },
        async mounted(){

            await this.starter();
        },
        methods:{
            async starter(){
                this.token = localStorage.getItem("tokenSaved");

                // this.tokenGennerate();
                if(this.token == null || this.token == ''){
                    await this.tokenGennerate();
                }

                console.log('token = '+this.token+" "+localStorage.getItem('tokenSaved'));

                await this.getContentList();
            },
            async getContentList(){

                let objectInstance = {
                    url: this.baseURL + 'URL',
                    method: 'get',
                    headers: {
                        "Content-Type" : "application/json",
                        "Authorization" : "Bearer " + this.token,
                        "Access-Code" : "QkQ%3D"
                    },
                };

                await axios(objectInstance).then((res) => {

                    // console.log(res.data._embedded.contents);
                    this.contentLists = res.data._embedded.contents;
                }).catch((error) => {
                    console.log('error'+error);
                    localStorage.setItem('tokenSaved', '');
                    this.starter();
                });
            },

            async tokenGennerate(){

                let objectInstance = {
                    url: this.baseURL + 'URL',
                    method: 'post',
                    // headers: {'X-Custom-Header': 'foobar'},
                    data: {
                        // data
                    }
                };

                // console.log(objectInstance);return;
                await axios(objectInstance).then((res) => {

                    this.token = res.data.token;
                    localStorage.setItem('tokenSaved', this.token);
                    // localStorage.setItem('tokenSaved',)
                }).catch(function (error) {
                    console.log(error);
                });

            }

        }
    }
</script>
```

**Comment by lmiller1990** [comment]
Have you tried to write a test? What have you gotten so far?

PS: Consider moving to `vue-test-utils`, it's the official lib for Vue testing. The creator of this lib is also the maintainer of it.

There is a collection of testing guides [here](https://lmiller1990.github.io/vue-testing-handbook/finding-elements-and-components.html#finding-components-with-name-and-component).
