### ISSUE TITLE
Test component's rendered elements against its parameters

### ISSUE THREAD

**Issue by wsielski** [eddyerburgh/avoriaz#117]
Considering the component rendering list of links based on Vuex state list of links. For the purpose of this question I'll make the code simpler and shorted but as clear as I can do:

LeftNav.vue
```
<template>
    <ul>
        <router-link to="/home" tag="li">Home</router-link>
        <router-link to="/xxx" tag="li">xxx</router-link>
    </ul>
</template>
```

leftnav.test.js
```
const linksExpected = ['/home', '/xxx'];
it('renders links with required parameters', () => {
    const LeftNavWrapper = mount(LeftNav);
    const links = LeftNavWrapper.find('router-link[tag="li"]');

    for (let i in links) {
        expect(links[i].someMethod('to', linksExpected[i]).to.be.true;
    }
});
```

I've tried to do this multiple way, unfortunately without success.

propsData()
computed() 

Can you please give me a hint how can I test it properly?

**Comment by eddyerburgh** [comment]
Try this:

```js
const routerLinkStub =  {
  name: 'router-link-stub'
}
Vue.component('router-link', routerLinkStub)
const linksExpected = ['/home', '/xxx'];

it('renders links with required parameters', () => {
    const LeftNavWrapper = mount(LeftNav);
    const links = LeftNavWrapper.find(routerLinkStub);

    for (let i in links) {
        expect(links[i].someMethod('to', linksExpected[i]).to.be.true;
    }
});
```

Let me know if it works (I haven't tested it)

**Comment by wsielski** [comment]
```
[avoriaz]: wrapper.find() must be passed a valid CSS selector or a Vue constructor
```
Well the problem is not a finding a right elements, but instead finding the right way to expose the parameters passed to them.

**Comment by eddyerburgh** [comment]
Sorry, I misunderstood your original problem.

There are two ways:

If the component has props defined in it:

```js
const routerLinkStub =  {
  name: 'router-link-stub',
  render: () => {},
  props: ['to']
}

expect(links[i].vm.to).to.equal(linksExpected[i]);
```

If the stub does not have props defined you need to use $attrs:

```js
const routerLinkStub =  {
  name: 'router-link-stub',
  render: () => {},
}

expect(links[i].vm.$attrs.to).to.equal(linksExpected[i]);
```

The second option is not ideal. I'll have to think about adding a method that allows this. Potentially I could edit `hasAttribute` to also include vm.$attrs. If you have any ideas for a method, I'd love to hear it.
