### ISSUE TITLE
AMD/UMD Support

### ISSUE THREAD

**Issue by Micene09** [eddyerburgh/avoriaz#119]
Hi,
I'm trying to develop a boilerplate using this library but, I cannot require it in a view using requirejs.
As I can see from the dist/avoriaz.js file, this needs just 3 dependencies:
- vue
- vue-add-globals
- lodash

...maybe this implementation will not be so hard, can you give it a try?

Ps. Thank you for the great job here man!

**Comment by eddyerburgh** [comment]
I've added umd and amd builds locally, but I'm not sure if they should include Vue. If they did, the dist files would be tied to whichever version of Vue avoriaz is using. I think the user should be able to choose which version they run.

I don't use umd/amd files often. Can you tell me a bit about your test pipeline. do you have an example project I can look at? Would you be able to include Vue seperately from avoriaz?

I think avoriaz should have avoriaz.umd and avoriaz.amd files that include lodash/cloneDeep and vue-add-globals, but not Vue.

What do you think?

**Comment by Micene09** [comment]
Totally agree with the inclusion of lodash/cloneDeep and vue-add-globals and the exclusion of Vue, every dev should be free to choose the Vue's version in every kind of environment...just think about the .min.js (production) and max version (dev with suggestions in console).

Actually i'm not ready to publish the boilerplate but, this is the project's configuration:
 - Karma as test runner
 - PhantomJS as browser
 - Mocha, Chai, Avoriaz as tests library

### About karma main (client) file
When test browser will be executed, this file will be injected.
This is the very entry point of the test environment, the reason why we put here the first require.config call, configuring the modules alias (require.config >> paths) to all the tests files + test library (chai, avoriaz).

### Tests boot
 - Test browser launcher executed
 - Karma inject plugins mocha and requirejs
 - Karma inject configurations in globals
 - Karma main file executed, first require.config done
 - All the tests files will be loaded and executed (via require, AMD).

### Test files
Every test file will be wrapped in define (requirejs) function as follow:

```javascript
define(["vue", "chai", "avoriaz", "/base/src/mycomponent"], function(Vue, chai, avoriaz, component) {
	// test assertions on component...
});
```

**Comment by eddyerburgh** [comment]
Ok, I've released a umd and amd build in 3.5.0

You can require with `'avoriaz/dist/avoriaz.amd.js'` or `'avoriaz/dist/avoriaz.umd.js'`

Can you let me know if this works correctly for you?

**Comment by Micene09** [comment]
Awesome!
It's working like a boss...i tried with both amd and umd version.

I was thinking about it, do we need really 2 files? amd and umd?
Maybe the umd is enought to cover every needs, what do you think about it?

**Comment by eddyerburgh** [comment]
Glad it's working ☺.

It's not much extra effort to have a umd and amd file, so I think we can
leave it.

On 25 Aug 2017 21:16, "Micene09" <notifications@github.com> wrote:

Awesome!
It's working like a boss...i tried with both amd and umd version.

I was thinking about it, do we need really 2 files? amd and umd?
Maybe the umd is enought to cover every needs, what do you think about it?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/eddyerburgh/avoriaz/issues/119#issuecomment-325024606>,
or mute the thread

**Comment by Micene09** [comment]
Ok man.
Thank you for the great job here.

Closing.
