### ISSUE TITLE
Testing `$watch` on `$route`

### ISSUE THREAD

**Issue by lmiller1990** [eddyerburgh/avoriaz#127]
Hi,

I have a test that is using a mock vuex store, and a real router. I want to test if an action is dispatched when the route changes.

I do something like:

SomeComponent:
```
export default {
  created() {
     this.$store.dispatch('someAction')
  },
  
  watch: {
    '$route' (newVal, val) {
        if (val.params.category !== newVal.params.category) {
          this.$stoore.dispatch('someAction')
        }
    }
  }
    
```

Test
```
import router from '../real-router'

describe('SomeComponent', () => {
  let actions;
  let store;

  beforeEach(() => {  
    actions = {
      someAction: jest.fn() // also tried sinon.mock()
    }
    store = new Vuex.Store({ state: {}, actions })
  })

  it('calls action on route change', () => { 
    mount(SomeComponent, { store, router })

    router.push({ name: 'someNamedRoute', params: { category: { 'okok' }})
    
    expect(actions.someAction.mocks.length).toBe(2)
  })
 })
})
```

For some reason, even though the $watch on the $route _is_ triggering, the mock is not called again. I can confirm it _does_ work in the created hook.

Is there something that would stop the action in a watch/route hook being called? Am I missing something? Or should I write this test different? I want to test that when the route changes, the action is called.

I am happy to contribute again if needed!

Thanks.

**Comment by eddyerburgh** [comment]
I'm on mobile so can't debug, but have you checked what newVal and oldVal are? How do you know watch is being called?

**Comment by lmiller1990** [comment]
I put a console.log inside and it's called. I tried logging `this.$store.dispatch('someAction')` and get a promise - even when I mock the method, odd.

I'll put up a working example tomorrow night (24h from this post or so).

**Comment by eddyerburgh** [comment]
Did you resolve your issue?

**Comment by lmiller1990** [comment]
@eddyerburgh thanks for checking back in. I did not, and I made a quick reproduction. See here https://github.com/lmiller1990/avoriaz-router-test-bug

The files to look at are Ajax.vue and Ajax.test.js. I am using Jest for testing.

I am using `watch: { $route }`. When the route changes, I want to dispatch an action. I mock teh action, and assert it should be called once, but it is not. Putting a console.log confirms the $watch is indeed triggering.

Please take a look and let me know if I'm doing something wrong. I'd love to contribute if it turns out to be a bug.

Thanks!

**Comment by lmiller1990** [comment]
Reopening (see above comment for repro).

**Comment by lmiller1990** [comment]
It turned out I could solve this using `setTimeout` around the expectations. 

In response to this I wrote a guide in `vue-test-utils` so other people don't run into this problem.

Thanks!

**Comment by peteringram0** [comment]
For anyone else who comes across this issue it seems to be fixed without the need for vue-test-utils.

Working like the following:
````javascript
it('Should collapse on route change', function (end) {

        const wrapper = mount(Nav, { router });

        wrapper.vm.navExpanded = true;

        expect(wrapper.vm.navExpanded).toBe(true);

        wrapper.vm.$router.push('/about');

        setTimeout(() => {
            expect(wrapper.vm.navExpanded).toBe(false);
            end();
        }, 0);

    });
````

**Comment by AndreiDetenkov** [comment]
```
it('Should collapse on route change', async ( ) => {
        const router = new VueRouter({
          routes: [{ path: '/' }, { path: '/about' }],
        });

        const wrapper = mount(Nav, { router });

        wrapper.vm.navExpanded = true;

        expect(wrapper.vm.navExpanded).toBe(true);

        await wrapper.vm.$router.push('/about');

        expect(wrapper.vm.navExpanded).toBe(false);
});
```
