### ISSUE TITLE
Vue.nextTick and vm data update

### ISSUE THREAD

**Issue by scleriot** [eddyerburgh/avoriaz#129]
Hi, 

First of all, thanks for this library ! :) 

I have this piece of code triggered by a click on a button.
```js
axios.put('/api/planning/bookings/'+this.eventid)
.then(response => {
    this.event.firm = !this.event.firm
})
```

I'm trying to test it with this code (axios request is stubbed with sinon) : 
```js
it('changes firm value on click', function(done) {
    let before = vm.event.firm
    btn.trigger('click')
    setTimeout(async function() {
        expect(vm.event.firm).to.not.be.equal(before)
        done()
    }, 500)
})
```

The value of `vm.event.firm` doesn't change, so the test fails. The following code passes the test : 
```js
it('changes firm value on click', async function() {
    let before = vm.event.firm
    btn.trigger('click')
    await setTimeout(async function() {
        await Vue.nextTick()
        expect(vm.event.firm).to.not.be.equal(before)
    }, 500)
})
```

I have to wait for Vue.nextTick() to have the vm data updated, any idea why ? (I don't see Vue.nextTick being used in this example https://eddyerburgh.gitbooks.io/avoriaz/content/api/mount/update.html)

**Comment by eddyerburgh** [comment]
Try using `update` to force update the value inside the setTimeout -
 https://eddyerburgh.gitbooks.io/avoriaz/content/api/mount/update.html

**Comment by scleriot** [comment]
My bad, I wasn't waiting for another request to complete... It's working as expected now, thanks
