### ISSUE TITLE
Method 'find' doesn't work with usual object.

### ISSUE THREAD

**Issue by kryvonos-redvike** [eddyerburgh/avoriaz#134]
My vue components are defined as usual objects, thus files of components have **js** extenstion.
So when I try to do something like this:
```javascript
import { mount } from 'avoriaz';
import Foo from './Foo.js';
import Bar from'./Bar.js'

const wrapper = mount(Foo);
const bar = wrapper.find(Bar)[0];
```

I get following error:
`wrapper.find() must be passed a valid CSS selector or a Vue constructor`

**Comment by eddyerburgh** [comment]
Can you post an example of Bar?

**Comment by kryvonos-redvike** [comment]
Simple example:
Foo.js
```javascript
import Bar from '@/components/Bar'

export default {
  name: 'Foo',
  components: { Bar },
  template: `
    <div>
      Foo component
      <bar></bar>
    </div>
  `
}
```

Bar.js
```javascript
export default {
  name: 'Bar',
  template: `
    <div>
      Bar component
    </div>
  `
}
```

**Comment by eddyerburgh** [comment]
avoriaz requires components to have a render function.

You can do this:

```
const compiler = require('vue-template-compiler')
import bar from '../src/components/Bar.js'

const BarRender = compiler.compileToFunctions(bar.template, bar)
const Bar = Object.assign(bar, BarRender)
```

and then use Bar like normal. 

This is a pretty poor solution, so I think we should add an option to avoriaz that does this for you. Something like `compile`.

I can't make a PR for at least the next week, so if anyone wants to pick it up, it would be much appreciated. 

If not, I'll get it added soon.

**Comment by eddyerburgh** [comment]
avoriaz now supports this in version 6.0.0 🎉
