### ISSUE TITLE
how to test correctly computed properties with Vuex getters ?

### ISSUE THREAD

**Issue by erwin16** [eddyerburgh/avoriaz#140]
Can you give some advices on testing w Vuex getters ... 

**Console log** upon running npm run unit, error in before each hook :

    `App.vue
		    display and add a new shopping list
		      ✗ "before each" hook for "displays Shopping Lists"
		        Error: [vuex] getters should be function but "getters.shoppinglists" is "getLists".
		            at assert (webpack:///~/vuex/dist/vuex.esm.js:97:19 <- index.js:1794:27)
		            at webpack:///~/vuex/dist/vuex.esm.js:252:0 <- index.js:1949:7
		            at webpack:///~/vuex/dist/vuex.esm.js:85:43 <- index.js:1782:52
		            at Array.forEach (<anonymous>)
		            at forEachValue (webpack:///~/vuex/dist/vuex.esm.js:85:0 <- index.js:1782:20)
		            at webpack:///~/vuex/dist/vuex.esm.js:251:0 <- index.js:1948:5
		            at Array.forEach (<anonymous>)`

**App.vue**

    `<template>
		  <div id="app" class="container">
		    <ul class="nav nav-tabs" role="tablist">
		      <li :class="index===shoppinglists.length-1 ? 'active' : ''" v-for="(list, index) in shoppinglists"  :key="list.id"  role="presentation">
		        <shopping-list-title-component :id="list.id" :title="list.title"></shopping-list-title-component>
		      </li>
		      <li>
		        <a href="#" @click="addShoppingList">
		          <i class="glyphicon glyphicon-plus-sign"></i>
		        </a>
		      </li>
		    </ul>
		    <div class="tab-content">
		      <div :class="index===shoppinglists.length-1 ? 'active' : ''" v-for="(list, index) in shoppinglists"  :key="list.id"  class="tab-pane" role="tabpanel" :id="list.id">
		        <shopping-list-component :id="list.id" :title="list.title" :items="list.items"></shopping-list-component>
		      </div>
		    </div>
		  </div>
		</template>

		<script>
		  import ShoppingListComponent from './components/ShoppingListComponent'
		  import ShoppingListTitleComponent from './components/ShoppingListTitleComponent'
		  import store from './vuex/store'
		  import { mapGetters, mapActions } from 'vuex'
		  import _ from 'underscore'

		  export default {
		    components: {
		      ShoppingListComponent,
		      ShoppingListTitleComponent
		    },
		    computed: mapGetters({
		      shoppinglists: 'getLists'
		    }),
		    methods: _.extend({}, mapActions(['populateShoppingLists', 'createShoppingList']), {
		      addShoppingList () {
		        let list = { title: 'New Shopping List', items: [] }
		        this.createShoppingList(list)
		      }
		    }),
		    store,
		    mounted: function () {
		      this.$nextTick(function () {
		        this.populateShoppingLists()
		      })
		    }
		  }
		</script>
`

**App.spec.js**

    `import App from '@/App'
		import Vue from 'vue'
		import Vuex from 'vuex'

		import sinon from 'sinon'

		import { mount } from 'avoriaz'

		Vue.use(Vuex)

		describe('App.vue', () => {
		  let actions
		  let getters
		  let store

		  describe('display and add a new shopping list', () => {
		    beforeEach(() => {
		      actions = {
		        deleteShoppingList: sinon.stub(),
		        populateShoppingLists: sinon.stub(),
		        createShoppingList: sinon.stub(),
		        addShoppingList: sinon.stub()
		      }
		      getters = {
		        shoppinglists: 'getLists'
		      }
		      store = new Vuex.Store({
		        state: { shoppinglists: [] },
		        actions,
		        getters
		      })
		    })
		    it('gets the Shopping Lists', () => {
		      const wrapper = mount(App, store)
		      expect(wrapper.computed().getLists()).to.equal('shoppinglists')
		    })
		  })
		})`

**Comment by eddyerburgh** [comment]
Replace this line:
```js
const wrapper = mount(App, store)
```
with: 
```js
const wrapper = mount(App, {store})
```

And make the getters a function that returns the value you want:
```
getters = {
  shoppinglists: () => 'getLists'
}
```
If this doesn't work, please open an issue on StackOverflow. The issue tracker is for bugs or feature requests.
