### ISSUE TITLE
Update the website documentation

### ISSUE THREAD

**Issue by WilliamDASILVA** [eddyerburgh/avoriaz#142]
Hi there,

The current documentation here: https://eddyerburgh.gitbooks.io/avoriaz/content/api/mount/hasAttribute.html does not represent the documentation specified here https://github.com/eddyerburgh/avoriaz/commits/master/docs/api/mount/hasAttribute.md

Since the changes are merged in master, wouldn't be better to update the website documentation more often to reflect the documentation in the repo ?

**Comment by eddyerburgh** [comment]
Agreed, thanks for reminding me.

I just republished. I'll add the publish script to the release script.

**Comment by eddyerburgh** [comment]
Closed with e44e789280cfdfd342259db8414d6e8a0643beaf
