### ISSUE TITLE
cannot test a custom directive plugin

### ISSUE THREAD

**Issue by erwin16** [eddyerburgh/avoriaz#144]
in the test specss, when we import the plugin, the install function is run , so it's before wrapping the Vue
( Vue.use(VueNoiseGeneratorPlugin) before wrapper = mount(App) )

so the Vue. directive cannot be initialized correctly

here is my unit test

VueNoiseGeneratorPlugin.spec.js

		import Vue from 'vue'
		import App from '@/App'
		import VueNoiseGeneratorPlugin from '@/plugins/VueNoiseGeneratorPlugin'

		import sinon from 'sinon'
		import { mount } from 'avoriaz'

		Vue.use(VueNoiseGeneratorPlugin)
		...

		describe('VueNoiseGeneratorPlugin', () => {
		  let wrapper
		  let audioContext = sinon.mock(new (window.AudioContext || window.webkitAudioContext)())

		  beforeEach(() => {
		    wrapper = mount(App)
		  })

		  it('should start noise', () => {
		    console.log('WRAPPER DATA: ', wrapper.data())
		    expect(wrapper.data().noiseColor).to.equal('brown')
		    Vue.noise.start()
		    audioContext.expects('resume').once()
		  })
		})

here is the console.log

		INFO [HeadlessChrome 0.0.0 (Mac OS X 10.13.0)]: Connected on socket 99D_HjLOfNIyKrtoAAAA with id 91092969
		LOG LOG: 'generate white noise'
		LOG LOG: 'generate default white'
		LOG LOG: 'WRAPPER DATA: ', Object{kittens: true, noiseColor: 'brown'}
		LOG LOG: 'method start called'

As we can see , the noise color generation is performed before wrapping, so the noiseColor data is ndefined , and the default color ( white ) is taken for noise generation... so I cannot test other colors...

here is the plugin 

VueNoiseGeneratorPlugin.js

		import _ from 'underscore'

		// Thanks to this great tutorial: http://noisehack.com/generate-noise-web-audio-api/
		var audioContext, bufferSize, noise
		audioContext = new (window.AudioContext || window.webkitAudioContext)()

		function generateWhiteNoise () {
		  console.log('generate white noise')
		  var noiseBuffer, output

		  bufferSize = 2 * audioContext.sampleRate
		  noiseBuffer = audioContext.createBuffer(1, bufferSize, audioContext.sampleRate)

		  output = noiseBuffer.getChannelData(0)
		  _.times(bufferSize, i => {
		    output[i] = Math.random() * 2 - 1
		  })

		  noise = audioContext.createBufferSource()
		  noise.buffer = noiseBuffer
		  noise.loop = true
		  noise.start(0)

		  return noise
		}

		function generatePinkNoise () {
		  console.log('generate pink noise')
		  bufferSize = 4096
		  noise = (function () {
		    var b0, b1, b2, b3, b4, b5, b6, node
		    b0 = b1 = b2 = b3 = b4 = b5 = b6 = 0.0
		    node = audioContext.createScriptProcessor(bufferSize, 1, 1)
		    node.onaudioprocess = function (e) {
		      var output

		      output = e.outputBuffer.getChannelData(0)
		      _.times(bufferSize, i => {
		        var white = Math.random() * 2 - 1
		        b0 = 0.99886 * b0 + white * 0.0555179
		        b1 = 0.99332 * b1 + white * 0.0750759
		        b2 = 0.96900 * b2 + white * 0.1538520
		        b3 = 0.86650 * b3 + white * 0.3104856
		        b4 = 0.55000 * b4 + white * 0.5329522
		        b5 = -0.7616 * b5 - white * 0.0168980
		        output[i] = b0 + b1 + b2 + b3 + b4 + b5 + b6 + white * 0.5362
		        output[i] *= 0.11 // (roughly) compensate for gain
		        b6 = white * 0.115926
		      })
		    }
		    return node
		  })()

		  return noise
		}

		function generateBrownNoise () {
		  console.log('generate brown noise')
		  bufferSize = 4096

		  noise = (function () {
		    var lastOut, node

		    lastOut = 0.0
		    node = audioContext.createScriptProcessor(bufferSize, 1, 1)
		    node.onaudioprocess = function (e) {
		      var output = e.outputBuffer.getChannelData(0)
		      _.times(bufferSize, i => {
		        var white = Math.random() * 2 - 1
		        output[i] = (lastOut + (0.02 * white)) / 1.02
		        lastOut = output[i]
		        output[i] *= 3.5 // (roughly) compensate for gain
		      })
		    }
		    return node
		  })()

		  return noise
		}

		export default {
		  install: function (Vue) {
		    Vue.directive('noise', (value) => {
		      var noise
		      switch (value) {
		        case 'white':
		          noise = generateWhiteNoise()
		          console.log('generate white')
		          break
		        case 'pink':
		          noise = generatePinkNoise()
		          console.log('generate pink')
		          break
		        case 'brown':
		          noise = generateBrownNoise()
		          console.log('generate brown')
		          break
		        default:
		          noise = generateWhiteNoise()
		          console.log('generate default white')
		      }
		      noise.connect(audioContext.destination)
		      audioContext.suspend()
		    })
		    Vue.noise = {
		      start () {
		        console.log('method start called')
		        audioContext.resume()
		      },
		      pause () {
		        console.log('method pause called')
		        audioContext.suspend()
		      },
		      stop () {
		        console.log('method stop called')
		        audioContext.suspend()
		      }
		    }
		  }
		}

and here is the App.vue

		<template>
		  <div id="app" class="container" v-noise="noiseColor">
		    <h2>
		      <span>{{ 'Pomodoro' | uppercase | addspace }}</span>
		      <controls-component></controls-component>
		    </h2>
		    <state-title-component v-bind:isWorking="isWorking"></state-title-component>
		    <countdown-component></countdown-component>
		    <transition name="fade">
		      <kittens-component v-show="!isWorking"></kittens-component>
		    </transition>
		  </div>
		</template>

		<style scoped>
		  .fade-enter-active, .fade-leave-active {
		    transition: opacity .5s
		  }
		  .fade-enter, .fade-leave-active {
		    opacity: 0
		  }
		</style>

		<script>
		import ControlsComponent from './components/ControlsComponent'
		import CountdownComponent from './components/CountdownComponent'
		import KittensComponent from './components/KittensComponent'
		import StateTitleComponent from 'a./components/StateTitleComponent'

		import store from './vuex/store'
		import { mapGetters } from 'vuex'

		window.data = {
		  kittens: true,
		  noiseColor: 'brown'
		}

		export default {
		  store,
		  components: {
		    ControlsComponent,
		    CountdownComponent,
		    KittensComponent,
		    StateTitleComponent
		  },
		  computed: mapGetters({
		    isWorking: 'isWorking'
		  }),
		  data () {
		    return window.data
		  }
		}
		</script>

**Comment by erwin16** [comment]
reading this closed issue ..

https://github.com/eddyerburgh/avoriaz/issues/32

I guess that I have to use avoriaz.use() rather than Vue.use()  ?   is it described in the doc ?

**Comment by eddyerburgh** [comment]
`avoriaz.use` doesn't exist anymroe. Vue.use will work.

I'll look into this properly soon (maybe Thursday), sorry for the delay

**Comment by erwin16** [comment]
solved issue  , in the plugin , I need to replace the parameter  value  :

    Vue.directive('noise', (value) => {
	      var noise
	      switch (value) {
             ....

with  :  binding.value 

         Vue.directive('noise', (el, binding, vnode) => {
              const noisecolor = binding.value
             var noise
             switch (noisecolor) {
                    ...
    
    Then the plugin spec using avoriaz is the following ( I'm looping the text over different noisecolor values

		import Vue from 'vue'
		import App from '@/App'
		import VueNoiseGeneratorPlugin from '@/plugins/VueNoiseGeneratorPlugin'

		import sinon from 'sinon'
		import { mount } from 'avoriaz'

		Vue.use(VueNoiseGeneratorPlugin)
		Vue.filter('addspace', (value) => {
		  return value + ' '
		})
		Vue.filter('uppercase', (key) => {
		  return key.toUpperCase()
		})
		Vue.filter('leftpad', (value) => {
		  if (value >= 10) {
		    return value
		  }
		  return '0' + value
		})

		const testValues = ['', 'white', 'brown', 'pink']
		let audioContext = sinon.mock(new (window.AudioContext || window.webkitAudioContext)())
		let wrapper = mount(App, { attachToDocument: true })

		const _fnStart = (value) => {
		  return describe('My Plugin', () => {
		    return it('should run start', () => {
		      wrapper.setData({ noisecolor: value })
		      Vue.noise.start()
		      audioContext.expects('resume').once()
		    })
		  })
		}
		const _fnPause = (value) => {
		  return describe('My Plugin', () => {
		    return it('should run pause', () => {
		      wrapper.setData({ noisecolor: value })
		      Vue.noise.pause()
		      audioContext.expects('suspend').once()
		    })
		  })
		}
		const _fnStop = (value) => {
		  return describe('My Plugin', () => {
		    return it('should run stop', () => {
		      wrapper.setData({ noisecolor: value })
		      Vue.noise.stop()
		      audioContext.expects('suspend').once()
		    })
		  })
		}
		for (let _i = 0, _len = testValues.length; _i < _len; _i++) {
		  const value = testValues[_i]
		  _fnStart(value)
		  _fnPause(value)
		  _fnStop(value)
		}
