### ISSUE TITLE
Trigger select

### ISSUE THREAD

**Issue by mgmalana** [eddyerburgh/avoriaz#146]
Hello, how do I trigger a checkbox?

My html is the ff:
          
```
<div class="list-checkbox">
    <input v-bind:value="ao.pk" type="checkbox" v-model="checkedAOs">
</div>
```

I tried checking the checkbox using:
`  wrapper.first('.list-checkbox input').trigger('click')`

The v-model should change but it doesn't. Any help on this?

**Comment by signal-intrusion** [comment]
Same problem with radio buttons.

**Comment by signal-intrusion** [comment]
@mgmalana It turns out you have to trigger change on the `input` element. Should work with `select` too.

```
const input = wrapper.find('#schedule-call-radio input')[1]
input.trigger('click')
const eventObject = new window.Event('change')
input.element.dispatchEvent(eventObject)
```

`.trigger('change')` isn't supported yet, but I bet it would be a quick fix.
