### ISSUE TITLE
Testing of computed properties

### ISSUE THREAD

**Issue by ryanjgill** [eddyerburgh/avoriaz#15]
When trying to test a computed property using AVA and with Avoriaz, the context of `this` is not what is expected. I'm trying to use a computed property that is based on some data from the component. 

More details on [stackoverflow](http://stackoverflow.com/questions/42768924/test-computed-property-in-vue-js-using-ava-with-avoriaz).

**Comment by eddyerburgh** [comment]
Three potential solutions here:

1. Remove computed, propsData and methods methods, since they return methods that are not bound to the vue instance, and encourage use of wrapper.vm 
```
const wrapper = mount(Component, {computed: { someMethod }})
expect(wrapper.vm.someMethod).to.equal(someMethod) // true :)
``` 
2. Bind all methods returned from computed(), methods() and propsData() to the vm instance. This means you couldn't do something like this:
```
function someMethod(){
  console.log(this)
}
const wrapper = mount(Component, {computed: { someMethod }})
expect(Component.computed().someMethod).to.equal(someMethod) // throws assertion error
```
That's not ideal.
3. Most radical - remove computed, methods and propsData methods and change the root of the wrapper to be the vue instance with added avoriaz methods. The vue instance(vm) already supports easy checking of methods and data:
```
const wrapper = mount(Component, {computed: { someMethod }})
expect(wrapper.someMethod).to.equal(someMethod) // true
``` 
This seems like the best solution to me, but it raises a couple issues - 
1. avoriaz methods could clash with component data or methods (ie. a component with a find method will clash with the avoriaz find method)
2. It's not really a wrapper anymore

**Comment by eddyerburgh** [comment]
@atilacamurca @stephane thoughts on the above?

**Comment by atilacamurca** [comment]
I agree with you, you should always keep it a wrapper.

**Comment by eddyerburgh** [comment]
@ryanjgill I can't think of a good way of fixing this. Instead I've added a warning that points to this issue and suggest using wrapper.vm.methodName to access computed functions that use this.

**Comment by ryanjgill** [comment]
@eddyerburgh Sounds good. Thanks for all the feedback guys!

**Comment by jasperck** [comment]
I was writing tests for my vue component,
when I tried to test the part of props, I was doing something like this
```js
given(
  ...some test data
)
  .it('should accept prop:', (propName, propValue) => {
    const wrapper = mount(InfiniteScroller, {
      propsData: { propName: propValue }
    });
    expect(wrapper.propsData().propName).to.equal(propValue);
  });
```
Then I got this warning messages and found out the reason in the issue from the messages.
```
WARN: 'warning: functions returned by propsData() will not have this bound to the vue instance. Calling a propsData function that uses this will result in an error. You can access propsData functions by using the vue instance. e.g. to call a method function named propsDataFunc, call wrapper.vm.propsDataFunc(). See https://github.com/eddyerburgh/avoriaz/issues/15'
```
According to the comment https://github.com/eddyerburgh/avoriaz/issues/15#issuecomment-289435469, looks like there is still no solution for somethink like
```js
expect(wrapper.vm.propName).to.equal(propValue);
```
am I right, guys?

**Comment by eddyerburgh** [comment]
@jasperck Both of your examples should work. The warning message is only meant for users trying to call propsData that use this.

**Comment by jasperck** [comment]
@eddyerburgh Thanks, I see, but actually it only worked for 
```js
expect(wrapper.propsData().propName).to.equal(propValue);
```
but not
```js
expect(wrapper.vm.propName).to.equal(propValue);

// test output
expected undefined to equal `propValue`
```
calling prop directly on `vm` just caused some error about getting `undefined`

**Comment by eddyerburgh** [comment]
@jasperck Hi, sorry for the miselading message. I've updated and released a correct warning message in 1.9.4.

To access props with this bound the vue instance, you must run: 

```
expect(wrapper.vm.$props.propName).to.equal(propValue);
```

**Comment by disitec** [comment]
Hi.

I am trying to follow the steps in the warning in order to check a computed but I get an error 
`TypeError: wrapper.vm.welcomeText is not a function`

and this is the code 

`t.is(wrapper.vm.welcomeText(), 'INTRODUCTION TEXT HERE');`

Of course, the computed exists in the component.

**Comment by eddyerburgh** [comment]
@disitec computed properties are called and the result saved to the vm.

```js
t.is(wrapper.vm.welcomeText, 'INTRODUCTION TEXT HERE');
```

Should pass

**Comment by disitec** [comment]
Yep, It works.

So, I think you shuould update the warning without parenthesis ;)

Thanks!

**Comment by eddyerburgh** [comment]
Fancy making a PR? 😉

**Comment by disitec** [comment]
Here you have. 

https://github.com/eddyerburgh/avoriaz/pull/63
