### ISSUE TITLE
External JS files "not defined"

### ISSUE THREAD

**Issue by Snugug** [eddyerburgh/avoriaz#158]
Using https://github.com/eddyerburgh/avoriaz-ava-example as a starting point, if I move the JavaScript from a single-file component from the actual `.vue` file to an external `.js` file and import it via `<script src="./foo.js></script>`, Vue throws warnings `[Vue warn]: Property or method "msg" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.`. This is a valid way of including JS in a Single File Component and for more complex components is almost a requirement.

Is there a setting I'm missing for how to get this to work?

**Comment by eddyerburgh** [comment]
This isn't supported at the moment, sorry.

I'd recommend against importing it in a script tag, and instead import it with es6/ commonjs.
