### ISSUE TITLE
Is this project deprecated in favor of vue-test-utils now?

### ISSUE THREAD

**Issue by kris-luminar** [eddyerburgh/avoriaz#177]
The main README says:

> This library will be deprecated once vue-test-utils is released.

https://github.com/eddyerburgh/avoriaz#deprecation

Judging from how the vue-test-utils project looks, I think maybe that has already occurred.
https://github.com/vuejs/vue-test-utils

Anyone know for sure?

**Comment by eddyerburgh** [comment]
Hey, vue-test-utils is still in beta, but I spend almost all my  time working on that project. avoriaz hasn't been officially deprecated yet, but I recommend using vue-test-utils

**Comment by kris-luminar** [comment]
Awesome--appreciate the info and all your hard work on those two testing libraries!
