### ISSUE TITLE
vue-test-utils 1.0.0-beta.11 setData Error

### ISSUE THREAD

**Issue by OneIsAll-L** [eddyerburgh/avoriaz#180]
First use, encountered setData problem.Ask everyone for help.
my code：
`it('setData()方法', () => {
    const wrapper = mount(Counter)
    wrapper.setData({foo: 'bar'})
    expect(wrapper.vm.foo).to.equal('bar')
  })`
terminal：
`setData()方法
     Counter.vue
     AssertionError: expected undefined to equal 'bar'
    at Context.<anonymous> (webpack:///test/unit/specs/Counter.spec.js:81:30 <- index.js:12255:31)`

**Comment by eddyerburgh** [comment]
Hey, this is the repo for avoriaz.

Try updating to @vue/test-utils beta.16:

`npm i -D @vue/test-utils`
