### ISSUE TITLE
import .vue files without extension

### ISSUE THREAD

**Issue by disitec** [eddyerburgh/avoriaz#23]
it is possible to import .vue files without requiring the extension? I have a huge project and I never use the extension.

In webpack.config.js I have this line, but it seems not working

`extensions: ['.js', '.vue'],`

Thanks

**Comment by eddyerburgh** [comment]
Yes it is possible, here's an example project that tests with avoriaz and doesn't require a .vue extension - https://github.com/eddyerburgh/avoriaz-karma-mocha-example?files=1

**Comment by disitec** [comment]
I was using this repo eddyerburgh/avoriaz-mocha-example as starting point. I would use that instead.

Thanks!
