### ISSUE TITLE
Support for vue events

### ISSUE THREAD

**Issue by hank1732** [eddyerburgh/avoriaz#30]
I have got a component like the following one, and i need to test if it emits the right event .

Could this be supported?

```
<template>
  <button @click="handleClick">
    <slot></slot>
  </button>
</template>
<script>

export default {
  name: 'Button',
  methods: {
    handleClick(e) {
      this.$emit('click', e)
    }
  }
}
</script>
```

**Comment by eddyerburgh** [comment]
You can test like this:

```javascript
it('emits click when button is clicked', () => {
  const wrapper = mount(Foo);
  const spy = sinon.spy(wrapper.vm, '$emit')
  wrapper.find('button')[0].simulate('click')
  expect(spy.args[0][0]).to.equal('click')
});
```
If people would like, I could add a method that returns the instance $emit function, although that would cause problems with `this`.

**Comment by eddyerburgh** [comment]
@hank1732 Can you confirm this solution worked?

**Comment by pearofducks** [comment]
Confirmed! For others in the future, the event payload is at `spy.args[0][1]`.
