### ISSUE TITLE
Vue.use accepts a second 'options' argument

### ISSUE THREAD

**Issue by ninechars** [eddyerburgh/avoriaz#32]
Despite what https://vuejs.org/v2/api/#Vue-use says, Vue.use() accepts two parameters. 

See spec here: https://github.com/vuejs/vue/blob/master/test/unit/features/global-api/use.spec.js

I found this while trying to initialise the excellent [vuex-i18n](https://github.com/dkfbasel/vuex-i18n) with `avoriaz.use(vuexI18n.plugin, store)`

**Comment by eddyerburgh** [comment]
Closed with #33 merge 🎉 

Thanks for the PR 😄
