### ISSUE TITLE
Slots throw vNode array exception

### ISSUE THREAD

**Issue by nerdyglasses** [eddyerburgh/avoriaz#34]
Hey @eddyerburgh, 

great library man!
Just upgraded to your latest version while trying out the slots.

I am following the docs from what I understand but `addSlots.js` is throwing an exception complaining that `slots[key]` should be an `Array` of `vNodes`.

I don't understand how this should work when the `Foo` component in the docs is an Object?

Ref: 
https://eddyerburgh.gitbooks.io/avoriaz/content/api/mount/#default-and-named-slots

```
import { mount } from 'avoriaz';
import { expect } from 'chai';]
import Foo from './Foo.vue';
import Bar from './Bar.vue';
import FooBar from './FooBar.vue';

describe('Foo', () => {
  it('renders a div', () => {
    const wrapper = mount(Foo, { 
        slots: {
            default: Bar,
            fooBar: FooBar // Will match <slot name="FooBar" />
        }
    });
    expect(wrapper.props(div)).to.equal(true);
  });
});
```

**Comment by eddyerburgh** [comment]
Hi, thanks 😁

The docs were outdated. I've just republished the updated version.

They should be passed as an array of v nodes. 

They need to be an array because there are cases where you can have multiple default (unnamed) slots.

I'm actually thinking of supporting the option to pass them as the previous example in the docs does. I think it's a better design. What do you think?

**Comment by nerdyglasses** [comment]
I don't even know how I can convert my component to an array of vNodes. Can you give me an example by what you mean?

**Comment by eddyerburgh** [comment]
You just need to put your component in an array 😃

```js
import { mount } from 'avoriaz';
import { expect } from 'chai';]
import Foo from './Foo.vue';
import Bar from './Bar.vue';
import FooBar from './FooBar.vue';

describe('Foo', () => {
  it('renders a div', () => {
    const wrapper = mount(Foo, { 
        slots: {
            default: [Bar],
            fooBar: [FooBar] // Will match <slot name="FooBar" />
        }
    });
    expect(wrapper.props(div)).to.equal(true);
  });
});
```

Sorry, I mean component, not vnode.

I'll update the docs to make it more clear.

**Comment by eddyerburgh** [comment]
In [1.13.0](https://github.com/eddyerburgh/avoriaz/releases/tag/1.13.0), you can now pass slots.name a Component or an array of Components 🚀
