### ISSUE TITLE
Trigger change event on input field

### ISSUE THREAD

**Issue by hauptrolle** [eddyerburgh/avoriaz#36]
Hey,

is it possible to trigger an change event on an input field with a given value?

`input.simulate('change', 'value')` and `input.simulate('change', { target: 'value' })` doesn't work and I don't find anything in the docs.

Thanks in advance. ✌️

**Comment by jraller** [comment]
The documentation does include `setData` https://eddyerburgh.gitbooks.io/avoriaz/content/api/mount/setData.html but I'm not sure if `setData` triggers a change event.

```
wrapper.setData({dataName: 'new value'});
```

**Comment by eddyerburgh** [comment]
Not yet, but it should do.

I'll look into adding this and update you when you can.

**Comment by hauptrolle** [comment]
First of all, thank you both for your fast response! 

@jraller: Your solution works, but if I change the data directly with setData, the change event is not necessary anymore because the data is already changed, and I don't test if the data changed when I only update the input.
Also I get an error when I use setData: `Cannot read property 'setValue' of undefined` But the stacktrace says this has to do with vuematerial. So it is not relevant here ...

@eddyerburgh: I have already tried this. It doesn't work 😢  Maybe you can take a look at reacts enzyme (https://github.com/airbnb/enzyme) and how they have implement the simulate :)

**Comment by eddyerburgh** [comment]
React has their own event system, separate from the DOM. This means they can let you edit event.target, because event isn't a real DOM Event. Enzyme uses the simulate method that react-test-addons exposes.

In avoriaz we send a real DOM event. For DOM events, target is read only. I'm not sure how to get around this.🤔

I briefly looked at simulant this morning - https://www.npmjs.com/package/simulant - as a potential solution.

I'll have a better look and get back to you 👍

**Comment by eddyerburgh** [comment]
I can't see a satisfactory way to fix this, apart from creating an entire event system - which would have lots of small bugs (events are complex!)

I've had success editing the DOM nodes value before calling simulate on it. 

This test is passing:

```js
    const changeHandler = sinon.stub();
    const value = 'value'
    const wrapper = mount(ChangeComponent, {
      propsData: { changeHandler },
    });
    wrapper.element.value = value;
    wrapper.simulate('change');

    expect(keydownHandler).to.be.calledOnce;
    expect(keydownHandler.args[0][0].target.value).to.equal('value')
```

Can you post the full component and test, so I can see what's going on?

**Comment by eddyerburgh** [comment]
@hauptrolle Have you found a way around this?

If not, could you post the component and test so I can test what's happening.

I've ran some tests, and setting the element value before simulating an event sends event.target.value as expected.

**Comment by hauptrolle** [comment]
@eddyerburgh Hey, sorry for the late response. It works as expected. 👍 
It seems to be an issue in the "vue-material" package I was using ...
