### ISSUE TITLE
Test fails when <router-view></router-view> is an element inside the component

### ISSUE THREAD

**Issue by megawubs** [eddyerburgh/avoriaz#41]
For the following component the test fails but succeeds when i remove the `<router-view></router-view>`

#### Teams.vue
```
<template>
    <div class="teams card">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Teams</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="team in teams">
                        <td>
                            <span v-show="!team.editing">{{team.name}}</span>
                            <input type="text" class="form-control" v-model="team.name" v-show="team.editing" />
                        </td>
                        <td>
                            <router-link :to="modalFor(team)">Edit</router-link>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <router-view></router-view>
    </div>
</template>

<script>
  import { Team } from '../../../models/team'
  import Modal from '../../../components/Modal'
  export default {
    components: {Modal},
    name: 'teams',
    mounted () {
      // load all teams
      Team.all().then(teams => {
        // disable editing mode for all teams
        teams.forEach(team => { team.editing = false })
        this.teams = teams
      })
    },
    data () {
      return {
        teams: [],
      }
    },
    methods: {
          modalFor (team) {
              return '/admin/teams/' + team.id
      }
    }
  }
```

#### Teams.spec.js

```
import Teams from '@/pages/dashboard/admin/Teams'
import { mount } from 'avoriaz'

describe('Teams.vue', () => {
  it('should render correct contents', () => {
    const wrapper = mount(Teams)
    const tableHeader = wrapper.find('.table tr th')[0]
    expect(tableHeader.text()).to.equal('Teams')
  })
})
```

#### The test result with the `<router-view>` inside the component:

![image](https://cloud.githubusercontent.com/assets/2302867/26168030/03e397c4-3b39-11e7-8258-652e1ce278e8.png)

#### The test result without the `<router-view>`
![image](https://cloud.githubusercontent.com/assets/2302867/26168080/2c3f51d6-3b39-11e7-80f4-5742204307ff.png)

**Comment by mcmillion** [comment]
Does it work if you pass a router into `mount` (import your router and then `mount(Teams, { router })`?

**Comment by megawubs** [comment]
when I import my router I get the following error

![image](https://cloud.githubusercontent.com/assets/2302867/26215177/9f254ebe-3bff-11e7-9337-49c343c386a4.png)

**Comment by eddyerburgh** [comment]
router-view is injected as a global component when you Vue.use() vue-router.

You need to register a mock global component:

```js
// mock component
const routerView = {
  name: 'router-view',
  render: h => h('div'),
};

// register mock component
Vue.component('router-view', routerView);
```

**Comment by megawubs** [comment]
thanks! That works 👍

**Comment by afontcu** [comment]
Hi there!

Sorry to reopen the issue but I'm failing to apply the code snippets you provided in the answers. 

This is my current configuration for the test:


```js
import Fixed from './Fixed'
import { shallow } from 'avoriaz'

// mock component
const routerView = {
  name: 'router-view',
  render: h => h('div')
}

describe('Fixed.vue', () => {
  it('is a component', () => {
    const vm = shallow(Fixed)

    // register mock component
    vm.component('router-view', routerView)

    expect(vm.isVueComponent).toBe(true)
  })
})
```

In my `Fixed.vue` component I'm using `this.$route.name` in a computed property, if it's of any help.

What am I doing wrong? I assumed your last answer (to mock the component) was right so I removed the `Vue.use(VueRouter)` stuff. Should I merge both things?



Thanks for your time and your work :)

**Comment by eddyerburgh** [comment]
Hi @afontcu . The return of shallow is actually a wrapper around a vm. You can access the `vm` with `wrapper.vm`

```js
const wrapper = shallow(Component)
wrapper.vm
```
But you need to register the component before you call shallow:

```
import Fixed from './Fixed'
import Vue from 'vue'
import { shallow } from 'avoriaz'

// mock component
const routerView = {
  name: 'router-view',
  render: h => h('div')
}

describe('Fixed.vue', () => {
  it('is a component', () => {
    Vue.component('router-view', routerView)
    const wrapper = shallow(Fixed)
    expect(wrapper.isVueComponent).toBe(true)
  })
})
```

Let me know if that works (I haven't tested so there may be an error :P

**Comment by afontcu** [comment]
Hi Edd,

first of all thanks for the quick response.

I switched both lines (the register and the shallow call) but it stills shows an error :(

```console
console.error node_modules/vue/dist/vue.common.js:436
      [Vue warn]: Error in render function: "TypeError: Cannot read property 'name' of undefined"

      (found in <Root>)
    console.error node_modules/vue/dist/vue.common.js:525
      TypeError: Cannot read property 'name' of undefined
          at VueComponent.shouldShowPath (/Users/.../Fixed/Fixed.vue:155:25)
```

(Taking the screenshot I realized that the tests actually shows green, but it still outputs console errors. I checked and happened the same when both lines were in the wrong order, so it's not new).


Thanks again!

**Comment by eddyerburgh** [comment]
It looks like an error in fixed on line 155. 

Are you trying to access a 'name' prop of an undefined object? Maybe you aren't passing in propsData to the component? It might be a problem with avoriaz, or the code I gave you, but check Fixed.vue line 155

**Comment by afontcu** [comment]
Hi!

The only `.name` access I'm doing in that component is in `this.$route.name`. The undefined in my test object is precisely `this.$route`, which makes sense. It works fine when running the app.

If I delete the line my test passes without console errors, so I'm quite sure the issue is about the route object.


The thing is - I'm doing something similar to this (not exactly, but for the sake of brevity):

```js
computed: {
    shouldShowPath () {
      return this.$route.name !== 'home'
    }
}
```

I might be designing the tests wrongly (or even the component!). Should I just "mock the computed property", instead of trying to mocking the route object? Can I do that?


Thanks!

**Comment by eddyerburgh** [comment]
You can mock `$route` 😄 

```js
describe('Fixed.vue', () => {
  it('is a component', () => {
    const $route = {name: 'some name'}
    Vue.component('router-view', routerView)

    const wrapper = shallow(Fixed, {
      globals: { $route }
    })
    expect(wrapper.isVueComponent).toBe(true)
  })
})
```

`globals` adds properties to the Vue prototype, so they are accessible inside each `vm`.

**Comment by afontcu** [comment]
That did the trick! 🎉  

Thanks man. I assumed `this.$route` and `<router-view>` would be solved using the same technique.

Thanks for your patience!
