### ISSUE TITLE
Globals injector not overwrite $route object mount

### ISSUE THREAD

**Issue by Clauber-camilo** [eddyerburgh/avoriaz#42]
Hello guys, 
I'm trying to test a method in a component and this method uses `this.$route.path` of the component. But I've got some problems to overwrite this object in test.

My component 
```javascript

<template>  
</template>

<script>
    import modulesConfig from './modules.config'
    
    export default {
        data () {
            return {
                modules: modulesConfig,
                activeModule: null
            }
        },
        mounted () {
            this.selectDefault()
        },
        methods: {
            selectDefault () {
                const route = this.$route.path
                    .replace('/admin/', '')

                const [module] = route.split('/')

                this.activeModule = this.modules.find(item => item.slug === module)
            },
            goToModule (route) {
                this.$router.push(route)
            }
        }
    }

</script>
``` 

Spec  

```javascript 

import avoriaz, { mount } from 'avoriaz'
import sinon from 'sinon'
import { expect } from 'chai'

// Component
import ModuleOptions from '_common/components/modules-options/ModuleOptions.vue'

describe('Module Options component :: ', () => {
    it('Receive the current default module', () => {
        const $route = { path: '/admin/cms' }

        const wrapper = mount(ModuleOptions, {
            globals: {
                $route
            }
        })

        expect(wrapper.data().activeModule.name).to.be.equal('Webshop CMS')
    })
})
``` 

But my original method in component returns an undefined object for the `$route` 

<img width="197" alt="screen shot 2017-05-17 at 2 49 09 pm" src="https://cloud.githubusercontent.com/assets/20336937/26168444/774e79fa-3b10-11e7-9cf6-f582b1bbf0f6.png"> 

What I'm doing wrong? Thanks 😄

**Comment by eddyerburgh** [comment]
When you install `vue-router`, the `$route` and `$router` properties [are set globally with `defineProperty`](https://github.com/vuejs/vue-router/blob/4e3b377e2eb9fdb4bc097e428cb8dcfeff59c3bc/src/install.js#L12). Which means they can't be deleted. 

I think you're calling `Vue.use(Router)` somewhere in your tests. If you don't call `Vue.use(Router)` in your tests, the `globals` option should work as expected.

**Comment by Clauber-camilo** [comment]
@eddyerburgh  Thank you man, that works. 

In my index test file, I was importing my application bootstrap file. And in there, I had the `Vue.use(Router)` code line. 

I was importing the bootstrap file, to make my coverage consider my hole application. 😄 

I didn't find what you said to me in your docs. Maybe you could add it to the docs? 
Thanks for your help. 

Awesome library! 😄

**Comment by eddyerburgh** [comment]
Thanks 😄 .

I will when I find the time. And I'd welcome a PR if you wanted to add anything to the docs!

**Comment by bseib** [comment]
> When you install `vue-router`, the `$route` and `$router` properties [are set globally with `defineProperty`](https://github.com/vuejs/vue-router/blob/dev/src/install.js#L12). Which means they can't be deleted.
> 
> I think you're calling `Vue.use(Router)` somewhere in your tests. If you don't call `Vue.use(Router)` in your tests, the `globals` option should work as expected.

Sorry to post on old/closed issue, but for the next person -- the correct permalink for that line of code from comment https://github.com/eddyerburgh/avoriaz/issues/42#issuecomment-302528489 is: https://github.com/vuejs/vue-router/blob/4e3b377e2eb9fdb4bc097e428cb8dcfeff59c3bc/src/install.js#L12  There you can see what's going on.
