### ISSUE TITLE
Vue should be made a peerDependency

### ISSUE THREAD

**Issue by yyx990803** [eddyerburgh/avoriaz#44]
Using Vue as a nested dependency will potentially cause version mismatches between the copy of Vue used by the user's application code.

This would be a breaking change - I'm just keeping a record for the things that we might want to change before we ship the next version.

**Comment by eddyerburgh** [comment]
I didn't consider this would be a breaking change and released in a minor in 1.14.0.

Not sure it's worth reverting and releasing another minor/ patch -  the damage is already done.
