### ISSUE TITLE
Testing whether an event handler is called

### ISSUE THREAD

**Issue by mattixittam** [eddyerburgh/avoriaz#48]
I'd like to test whether an event handler is called. I thought this would work, but it doesn't:
```
it('handles the input event', () => {
    const wrapper = mount(UiInput)
    const handleInput = sinon.spy(wrapper.vm, 'handleInput')

    wrapper.find('input')[0].dispatch('input')

    expect(handleInput).to.be.calledOnce
})
```
(handleInput is a method on the UiInput component, and is bound by @input="handleInput" on the input element)

It is called 0 times. If I call the handler directly instead of dispatching the event, the expect returns true. Seems the dispatch does not trigger the v-on binding somehow? Any idea why this happens?

**Comment by eddyerburgh** [comment]
@mattixittam it should work if you add the spy to the component before you call `mount`:

```js
it('handles the input event', () => {
    const handleInput = sinon.spy(wrapper.vm, 'handleInput')
    const wrapper = mount(UiInput)

    wrapper.find('input')[0].dispatch('input')

    expect(handleInput).to.be.calledOnce
})
```

**Comment by mattixittam** [comment]
I've fixed it using a variation of your previous response:

```
it('handles the input event', () => {
    const handleInput = sinon.spy(UiInput.methods, 'handleInput')
    const wrapper = mount(UiInput)

    wrapper.find('input')[0].dispatch('input')

    expect(handleInput).to.be.calledOnce
})
```
This passes
