### ISSUE TITLE
Functional components

### ISSUE THREAD

**Issue by nekosaur** [eddyerburgh/avoriaz#49]
Is it possible to use avoriaz to test functional components? When I quickly tried it out earlier it gave me an error that the context parameter for the component's render function was undefined.

If I change the mounting to something like this
```javascript
new Vue({
  components: {
    Test: component
  },
  render (h) {
    return h('test', options)
  }
})
```
then I don't get the error message, but everything in `context.props` is undefined, like this.
```javascript
{
  prop1: undefined,
  prop2: undefined
}
```

**Comment by eddyerburgh** [comment]
I actually didn't consider functional components. I can have a look at it over the next few days, or if you want to look into it a PR would be appreciated!

**Comment by nekosaur** [comment]
I can continue to dig around, but I'd best mention that I'm not that knowledgeable about the internal workings of Vue so it might be more stumbling than digging.

**Comment by eddyerburgh** [comment]
Ok Albert, don't worry - I'll look into it. I might be able to find a way
tomorrow lunch.

**Comment by eddyerburgh** [comment]
Can you post the functional component that was throwing errors, and how you were passing it to mount?

Are you passing `props` or `propsData` inside `options`?

**Comment by nekosaur** [comment]
Here's a very simple functional component that I was testing with.

```javascript
{
  functional: true,
  render: (h, { data, children }) => {
    return h('div', data, children)
  }
}
```
I was mounting it like any other component.

```javascript
const wrapper = mount(Component)
```

It doesn't matter if I pass an options object with propsData or not, I always get this error.

```
TypeError: Cannot convert undefined or null to object
      at mount (node_modules/avoriaz/dist/mount.js:53:10)
      at Object.it (test/unit/specs/Avatar.spec.js:23:40)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by nekosaur** [comment]
Thank you! I've tested it and it works fine so far 👍
