### ISSUE TITLE
Cant mount component with required: true props

### ISSUE THREAD

**Issue by pablohpsilva** [eddyerburgh/avoriaz#5]
If I try to mount a component with: 
```javascript
    const id = 'hello';
    const url = 'bad thing';
    const wrapper = mount(Dropzone, {
      propsData: {
        id,
        url,
      },
    });
```
It fails to create it, because the component requires props to have a value. If I mount it using: 
```jvascript
const getComponentWithProps = (component, propsData) => {
  const Ctor = Vue.extend(component);
  return new Ctor({
    propsData,
  });
};
    const id = 'hello';
    const url = 'bad thang';
    const wrapper = getComponentWithProps(Dropzone, { id, url });
```

The wrapper has the instance of my component created. Any help? =X

**Comment by eddyerburgh** [comment]
Hi @pablohpsilva, I'm busy most of today but will take a look tomorrow and try to get a fix up asap

**Comment by pablohpsilva** [comment]
No worries. Thanks for this amazing project!

**Comment by eddyerburgh** [comment]
Hi @pablohpsilva. The example you provided creates an unmounted Vue component, which doesn't contain a vNode. Without a vNode most avoriaz methods won't work. If you try to call $mount on the Vue component, you will have the same problem as mounting it with avoriaz (an Error will be thrown).

What's the reason you want to mount a Component with required props without specifying the props when mounting?

As far as I understand - you can't mount a component that has a required prop if the prop isn't passed in propsData? Why can you not pass the prop? 

Can you post the component you're trying to mount?

**Comment by pablohpsilva** [comment]
Hello @eddyerburgh :D 
Let me give you a real example:

```javascript
export const getComponentWithProps = (Vue, component, propsData) => {
  const Ctor = Vue.extend(component);
  return new Ctor({
    propsData,
  });
};

const drop = getComponentWithProps(Vue, Dropzone, {
  id: 'some1231id',
  url: 'https://github.com',
}).$mount();
```
Like I shown before, I am passing the props the component requires, but its not working :( 
Is there a way to make it work with avoriaz?

**Comment by eddyerburgh** [comment]
Does this work:

```
avoriaz.mount(Dropzope, {
  propsData: {
    id: 'some1231id',
    url: 'https://github.com',
  }
})
```

**Comment by pablohpsilva** [comment]
That's really weird... I can swear I tried that before and now everything worked out.
Wow... OK! That's awesome! Thank you for your time and amazing tool @eddyerburgh ! :D
