### ISSUE TITLE
Sizzle throws error that window is not defined

### ISSUE THREAD

**Issue by timwis** [eddyerburgh/avoriaz#50]
Hello, I'm trying to use avoriaz with ava using a very basic example, even more basic than your ava example, but it's throwing an error that `window is not defined`, referencing sizzle. Any suggestions?

**Comment by eddyerburgh** [comment]
avoriaz needs a browser to run, like jsdom.

the avoriaz-ava example uses browserenv(which is a wrapper around jsdom) -

```
npm install --save-dev browser-env
```

Then, in a file that runs before your tests - 

```js
require('browser-env')()
```

Thanks for the issue, I'll add a check for window and throw a clearer error message 👍

**Comment by timwis** [comment]
Ah! Thanks for the quick reply
