### ISSUE TITLE
Event not being caught on child component?

### ISSUE THREAD

**Issue by mattixittam** [eddyerburgh/avoriaz#54]
It seems that when I do a dispatch() on a vue-component that is a child element of the component I'm testing, the event is either not fired at all or not caught by the vue event handler.

If I replace the ui-navigation-level component with a simple div, the event is caught.

This is the component (stripped to bare functionality):

```
<template>
    <ul class="ui-navigation">
        <ui-navigation-level
            :options="options"
            @select="handleSelect"
        ></ui-navigation-level>
    </ul>
</template>

<script>
    import NavigationLevel from './ui-navigation-level.vue'

    export default {
        name: 'ui-navigation',

        props: {
            options: {
                type: Array,
                required: true,
            },
        },

        components: {
            'ui-navigation-level': NavigationLevel,
        },

        methods: {
            handleSelect(option) {
                this.$emit('select', option)
            },
        },
    }
</script>
```
And the test:
```
it('handles the select event', () => {
    const handleSelect = sinon.spy(Navigation.methods, 'handleSelect')

    const wrapper = mount(Navigation, {
        propsData: {
            options: [
                /* ... */
            ],
        },
    })

    wrapper.find('.ui-navigation-level')[0].dispatch('select')

    expect(handleSelect).to.be.calledOnce //Result: called 0 times
})
```

**Comment by eddyerburgh** [comment]
Thanks for the bug report.

This should be fixed in v1.16.0.

Can you download from npm and confirm fix.

Note that dispatch has been deprecated in place of trigger (simple name change).

**Comment by mattixittam** [comment]
Tested, but bug is still there unfortunately.

**Comment by eddyerburgh** [comment]
In your test, can you try finding the component using the component:

```js
it('handles the select event', () => {
    const handleSelect = sinon.spy(Navigation.methods, 'handleSelect')

    const wrapper = mount(Navigation, {
        propsData: {
            options: [
                /* ... */
            ],
        },
    })

    wrapper.find(NavigationLevel)[0].dispatch('select')

    expect(handleSelect).to.be.calledOnce //Result: called 0 times
})
```

**Comment by mattixittam** [comment]
Yup, when finding using the component object, it works!

Hmm, found the (an) issue, I think. This returns _undefined_:

`wrapper.find('.ui-navigation-level')[0].isVueComponent`

**Comment by eddyerburgh** [comment]
Is there an element with class `ui-navigation-level` in the NavigationLevel component?

**Comment by mattixittam** [comment]
Yup

**Comment by eddyerburgh** [comment]
Thinking about this - it isn't a bug with avoriaz. 

Vue doesn't add event bindings added on components to the DOM.

If you want to add a click event listener, you need to do it inside the component on an element in the template. https://vuejs.org/v2/guide/events.html#Method-Event-Handlers

**Comment by eddyerburgh** [comment]
>Hmm, found the (an) issue, I think. This returns undefined:
wrapper.find('.ui-navigation-level')[0].isVueComponent

Vue components and DOM nodes are treated differently. If you use a DOM selector, it will return a vnode - not a vue instance.
