### ISSUE TITLE
ssr

### ISSUE THREAD

**Issue by stellanhaglund** [eddyerburgh/avoriaz#56]
Hi I just tried out your module and it seems to work very good.
Though I have a question I just made my first setup for a vue ssr app, and I was wondering if doing the tests like this is the best way for a universal app, or do you know of a better way?

**Comment by eddyerburgh** [comment]
You can unit test components with avoriaz the same as you would without ssr. ☺

You could add end to end tests with something like nightwatch that check the page is being returned correctly and behaves how you expect.

You could also add a test with something like supertest that checks you're returning html when you hit an endpoint.

**Comment by stellanhaglund** [comment]
Yeah, that was what I was thinking.

What i'm thinking is that if I have to check that the correct html is sent from the endpoint, then basically I run the same tests in two places.

I don't know how it's usually done, but maybe test the components with avoriaz to see that they are acting correctly and then do the bigger stuff like logging in and such with nightwatch then?

**Comment by eddyerburgh** [comment]
Yeah I'd test individual components with avoriaz, and the behavior of
multiple components with nightwatch :)

**Comment by stellanhaglund** [comment]
great thanks! :)
