### ISSUE TITLE
Exceptions are logged instead of thrown

### ISSUE THREAD

**Issue by chrisnicola** [eddyerburgh/avoriaz#58]
Right now because of Vue's built-in error handling, exceptions are logged to `console.error` rather than thrown. During test running it will generally make more sense for these errors to fail the tests, but as they are just logged this doesn't happen.

As a stopgap solution `Vue.config.errorHandler` can be set at the top of every test, but this is a bit less than ideal and it would be better if this could be configured through Avoriaz.

**Comment by eddyerburgh** [comment]
Good point. 👍

I'm busy the next few days but I'll try and get it done in the next week. Alternatively, I'll accept a PR if you want to contribute

**Comment by chrisnicola** [comment]
Sure thing. I'm working on a "webpack-runner" that works similar to `bin/tape` but processes all the files in the glob through webpack first before running them. It works a bit better than `vue-node` as that only processes `.vue` files.

One other thing I'm noticing is that I'm getting the `productionTip` notice even though I know `avoriaz` sets that to false before mounting. You've probably been working with Vue longer than I have. Any ideas why it might do that?

If I had to guess I'd wager that the Webpack result is somehow causing Vue to get loaded before Avoriaz mounts the component.

**Comment by eddyerburgh** [comment]
What version are you using?

**Comment by chrisnicola** [comment]
Of Avoriaz? 1.15.0.

Vue: 2.3.3

**Comment by chrisnicola** [comment]
I see, I just upgrade to 2.0.0 and it works now. I'll have that PR soon.

**Comment by eddyerburgh** [comment]
Hi @chrisnicola , are you still planning a PR for this?

**Comment by chrisnicola** [comment]
Hey Eddy, sorry I got busy getting some other infrastructure in place for our first Vue apps. I am and I'll try to do that today or this weekend.

**Comment by eddyerburgh** [comment]
Are you still planning on adding this?

**Comment by chrisnicola** [comment]
@eddyerburgh with the imminent transition to vue-test-utils is it still worth adding this?

**Comment by eddyerburgh** [comment]
Probably not
