### ISSUE TITLE
[Vue warn]: Cannot find element: #app

### ISSUE THREAD

**Issue by jacklp** [eddyerburgh/avoriaz#59]
// PROBLEM

Have loved using your your app!

It is throwing me a Vue Warning '[Vue warn]: Cannot find element: #app'

This is because I am mounting this component in a unit test so it obviously won't run the usual main.js set up class. I was wondering if the mount function has a way of putting it into a #app div to stop this annoying warning message. (this feels like a nice to have feature as everything is working fine)

// TEST CODE

import { expect } from 'chai'
import { mount } from 'avoriaz'
import TextInput from '../../../../src/widgets/TextInput.vue'
import {StringField} from 'mutt-forms/src/fields/text'

describe('TextInput.vue', () => {

    let wrapper = {}
    beforeEach(() => {

        // instantiate our model
        let test = StringField.new('test_id', "test_name", {"type":"string"}, {"label":"Dr Pookie from group 1"})

        // pass model in as a prop to vue component
        wrapper = mount(TextInput, {
            attachToDocument: true,
            propsData: {
                field: test
            }
        })
    })

    it('renders ok', function() {
        expect(wrapper.is('div')).to.equal(true)
    })
})

// VUE COMPONENT

<template>
    <div v-if="field" :class="getFieldWrapperClass()">
        <label-widget
            :field="field"
            :fieldId="getFieldId()"></label-widget>
        <input
            type="text"
            :name="field.name"
            :value="value"
            :class="getFieldClass()">
        <help-widget :field="field"></help-widget>
        <error-widget
            :field="field"
            :errors="errors"
            :errorClass="getErrorClass()"></error-widget>
    </div>
</template>

<script>
import LabelWidget from './helpers/Label.vue'
import ErrorWidget from './helpers/Error.vue'
import HelpWidget from './helpers/Help.vue'
import {WidgetProxy, DataProxy} from '../utils'

export default {
    name: 'mutt-text',
    props: ['field'],
    components: {
        LabelWidget,
        ErrorWidget,
        HelpWidget
    },
    created: function() {
        this.field.widget = this
    },
    data: DataProxy,
    methods: WidgetProxy
}
</script>

**Comment by eddyerburgh** [comment]
Can you post a minimal failing example that doesn't have any dependencies?

Then I can use it as a test case and write a fix that will let you mount it to a custom element ( I think that should fix the issue).

It's important I have a minimal example to find out what's causing the error and how to fix 👍

**Comment by eddyerburgh** [comment]
HI @jacklp, I'm closing this issue but happy to reopen if you can provide more detail.

What I think is happening is that you were trying to test a component that was had the `$el` option (aka the root component) set to `'#app'`. As this doesn't exist on the DOM you were testing on, it threw an error.

This could be solved by adding an element with an id of app to the body. 

I don't think any feature should be added to avoriaz to support this, as the root element should really be logic less. Although I'm happy to discuss this if anyone disagrees

**Comment by mboullouz** [comment]
Hi @eddyerburgh ,
we work on a "classical" web app where most views are generated in the server side, we added Vue to enhance user experience, we have all components bundled in one webpack big file that is included in every page (and obviously most components are not in the 'current' page).
My question: does it impact perfs or just Vue warn and ignore ?

**Comment by MetalNose** [comment]
@mboullouz I'm having the same issue :/

**Comment by res-paul-g** [comment]
@eddyerburgh same here

**Comment by wbarnard81** [comment]
Hi guys, came across this site via a google search. Even though I am not using this app, I am getting the same issue and I know why as well, but I am not sure how to resolve it yet.

I built my own app, using Laravel. One component that I want to use is DataTables. To get this working, I had to remove 'deferred' from [code]<script src="{{ asset('js/app.js') }}"></script>[/code] and since then, I am getting this error. Obviously, if I put deferred back, I don't get this error anymore, but then my datatables don't work anymore.

**Comment by crocodilered** [comment]
Same bug.

**Comment by antangible** [comment]
Same error.

**Comment by milad-4274** [comment]
same warn

**Comment by Alwongs** [comment]
Put the <script> in the bottom of body teg. For me, it helped
