### ISSUE TITLE
Nested vNodes are out of sync

### ISSUE THREAD

**Issue by roll** [eddyerburgh/avoriaz#6]
Consider a component with template like this:

```html
<div>
  <div>
    <div v-if="!ready"  class="not-ready">not-ready</div>
    <div v-else class="ready">ready</div>
  </div>
</div>
```

After `ready` change to `true` we will not be able to `wrapper.find('.ready')` because nested vNodes is not updated (it still will be `.not-ready` div). I was debugging it via `findAllVNodes`. This function is getting out-dated nested vNodes.

On the other hand `wrapper.html()` and `wrapper.text()` work correctly.

---

vue@2.1.10/2.2.1
avoriaz@1.6.0

**Comment by eddyerburgh** [comment]
Hi, I'll have a look and try to get a fix up by the end of the weekend

**Comment by roll** [comment]
Hi, great that's awesome! 

Unfortunately I'm pretty new to vue.js so can't help with ideas of solving it.

Looking forward to actively use this library at Open Knowledge International (https://github.com/okfn). In my opinion testing library like this should be a vital part of the vue.js eco-system.

**Comment by eddyerburgh** [comment]
How are you changing the data? Can you paste the component and the test here?

I wrote a test with the example you provided:

```vue
<template>
  <div>
    <div v-if="!ready"  class="not-ready">not-ready</div>
    <div v-else class="ready">ready</div>
  </div>
</template>

<script>
  export default {
    name: 'If',
    data: () => ({
        ready: false
    }),
  };
</script>
```

```javascript
    it('renders .ready when data.ready is changed', () => {
      const wrapper = mount(If);
      expect(wrapper.find('.not-ready').length).to.equal(1);
      wrapper.vm._data.ready = true;
      wrapper.update();
      expect(wrapper.find('.ready').length).to.equal(1);
    });
```

This obviously isn't ideal, so I will make a setData method that updates teh Vue instance after it has set data.

If you are setting the data differently (e.g. in a component method), I'll use your example as a test case and find a way to make it work with avoriaz. :smile:

**Comment by eddyerburgh** [comment]
Just release 1.7.0.

I've added a `setData` method.

The above code now looks like this:

```
it('renders .ready when data.ready is true', () => {
  const wrapper = mount(If);
  expect(wrapper.find('.not-ready').length).to.equal(1);
  wrapper.setData({ready: true});
  expect(wrapper.find('.ready').length).to.equal(1);
});
```

**Comment by roll** [comment]
@eddyerburgh 
Sorry for the slow answer - it seems I have invest more time for reproducing my problem. Closing before I've got working "non working" test case.

---

> Just release 1.7.0. :tada:
I've added a setData method.

:tada:
