### ISSUE TITLE
Shallow render - bypass lifecycle hooks

### ISSUE THREAD

**Issue by crcatala** [eddyerburgh/avoriaz#60]
First off super awesome stuff on the latest 2.1.0 release and shallow rendering 🙌  Been looking forward to that and thanks for all the effort in creating avoriaz!

I just checked out the shallow rendering, and for a case where a child component has some lifecycle hook, it will still get executed during test. For example a child component dispatching a vuex action on mount:

```javascript
export default {
  name: 'SomeChildComponent',
  mounted() {
    this.$store.dispatch('fetchUsers');
  }
};
```

This is expected, but would it be worth having a way to optionally bypass the lifecycle hooks so that testing the parent doesn't care about any of these potentially side effects?

**Comment by eddyerburgh** [comment]
Aha - great catch! I hadn't considered this. I'll get a 2.1.1 release today where all lifecycle eveMrs are stubbed. Thanks for the issue 😊

**Comment by eddyerburgh** [comment]
Also, is this expected? I think they should be stubbed by default

**Comment by crcatala** [comment]
@eddyerburgh cool looking forward to it! stubbed by default would make sense

**Comment by eddyerburgh** [comment]
This should be fixed in 2.1.1 👍

**Comment by crcatala** [comment]
Verified 💯 on super quick fix with test coverage!

**Comment by crcatala** [comment]
fixed in release 2.1.1
see c39ed7f37b7e90a6aff97781ca9537de55ef9de6

**Comment by rmartins90** [comment]
related to this: shallow seems to behave like mount should and vice-versa, is this possible? This happens for example on a child component that has watchers - if I use mount I get no errors related to child component, while using shallow return me errors related to that child watchers. Also, the same behaviour on router-link component. Am I missing something?

I'm using latest version (2.4.1). Thanks

**Comment by eddyerburgh** [comment]
@rmartins90 This could be a bug.

Could you please open a new issue with details of the component, test and errors. I'll see if I can fix the bug

**Comment by rmartins90** [comment]
Sure. Will do
