### ISSUE TITLE
Using both `shallow` and `mount` in a test causes everything to shallow render

### ISSUE THREAD

**Issue by mcmillion** [eddyerburgh/avoriaz#67]
First of all, thanks for adding `shallow`. This is totally cleaning up our tests!

I noticed today (and maybe this is by design, but I wanted to check to make sure), that if you include both `mount` and `shallow` in a single spec, `shallow` seems to take over.

While we've been using `shallow` in our new tests for our presentation components, we utilize `vue-svg-loader` for loading SVGs and using them as components. This of course requires the use of `mount`. What I've noticed is that one you include `shallow` in the spec, all uses of `mount` also shallow-render.

It's not a huge deal to just use `mount` in those specs, but I feel like I may be missing something. Any ideas?

**Comment by eddyerburgh** [comment]
Hi, that was indeed a bug.

Should be fixed in 2.2.1 👍
