### ISSUE TITLE
Router is not mounted after upgrading to 2.4.0

### ISSUE THREAD

**Issue by disitec** [eddyerburgh/avoriaz#70]
Hi,

I am getting errors in code that was working in previous versions. It could be a bug or I need to mount the component in a different way now?

```
const $route = { path: '/users/:id', params: { id: 4 } };
const globals = { $route };

const wrapper = shallow(AnswerBeat, { globals });
```

**Comment by eddyerburgh** [comment]
This sounds like a bug, there shouldn't have been any breaking changes in a minor version.

Can you post the component and full test for me to debug?

**Comment by eddyerburgh** [comment]
@disitec I'm keen to get this fixed, can you provide the component or a failing test?

**Comment by disitec** [comment]
Sorry for the delay. I am a bit busy, I'll try to reproduce it again and give you more information.

Thanks

**Comment by eddyerburgh** [comment]
No need to apologize 😊

I appreciate the help

**Comment by disitec** [comment]
I must say I can't reproduce it anymore. Maybe was a silly mistake in my side or maybe you fix it with another issue.

I close this. :octocat:
