### ISSUE TITLE
Can't stub $router in unit tests

### ISSUE THREAD

**Issue by chrisnicola** [eddyerburgh/avoriaz#80]
So I'm writing a test that does something like:

```
  t.stub($store);
  const $router = { push: t.spy() };
  const data = { email: 'test@wb.test', password: 'password' };
  const wrapper = mount(Login, { data, globals: { $router, $store } });
  t.stub($store, 'getters').value({ isLoggedIn: true });
```

And while the `$store` stub is available on `this` in the component the `$router` one is not set. I'm assuming there is some special behaviour with the `$router` global?

This is a unit test so I'm not installing `vue-router` or `vuex` in the tests, I'm stubbing them out using Sinon instead.

**Comment by eddyerburgh** [comment]
Are you sure you're not calling `Vue.use (VueRouter)` anywhere when you run your tests?

If you're using the vue webpage template, I'm the files are parsed by karma which causes vue router to be installed. This is my edited version of the file https://github.com/eddyerburgh/stub-route-in-vue-unit-tests/blob/master/test/unit/index.js. the comments weren't changed, so they are a bit confusing. In the template they require all src files except main, which includes router files that install vue router and set an immutable $router object. Ive changed the code to require all files in  the components dirextory.

Hopefully this solves your issue.

**Comment by eddyerburgh** [comment]
Accidentally closed (I'm  on mobile) 🙃

**Comment by chrisnicola** [comment]
Interestingly enough, I'm actually running it as an isolated unit test. So no Karma, or PhantomJS, just `browserEnv()` and `tape`. `this.$router` is actually undefined in the tests.

**Comment by eddyerburgh** [comment]
Would you be able to post a minimal reproduction of the test and component?

**Comment by chrisnicola** [comment]
Yeah I'll try to get something together next week.

**Comment by chrisnicola** [comment]
Sorry I haven't had time to get back into this. I'm definitely having a vue-router related problem. I'm also unable to stub `$route`. I don't have this problem with any other global variable name. I can call it `route` and it works.

As far as I know, I'm not installing `vue-router` as the only files that are compiled are test files. However it's possible that is happening, but the result of `wrapper.vm.$route` and `wrapper.vm.$router` is that they are undefined.

**Comment by chrisnicola** [comment]
Bah, I just realized I am installing the router at some point in the testing because I have tests that test the router and I'm using tape, so the environment is not entirely reset between tests.

I'll have to play with this a bit more. I wonder if Avoriaz could isolate itself from the global `Vue` but I'm guessing that would be hard.

**Comment by chrisnicola** [comment]
Ok I've ensured I don't install `Router` now I get errors about `router-link` not being registered.

**Comment by chrisnicola** [comment]
Ok I read the other issues and figured it out. I need to register a component stub. No problem. I get it now.

**Comment by eddyerburgh** [comment]
I'll write a guide for this at some point

**Comment by LoneRifle** [comment]
I'm currently unable to coax avoriaz to accept my mock router or router-link stubs, and so the tests insist that the router-link element is unknown. I've tried `shallow`, stubbing a router-link component manually and other functions all to no avail. If there's a guide that can walk me through this I'd be happy to give it a read.

**Comment by signal-intrusion** [comment]
@chrisnicola what other issues?

**Comment by signal-intrusion** [comment]
@eddyerburgh do you have that guide written o maybe just drop a couple lines in here to help unblock us. THANKS! 😄

**Comment by eddyerburgh** [comment]
This is a guide for vue-test-utils but it's the same concepts — https://vue-test-utils.vuejs.org/en/guides/using-with-vue-router.html
