### ISSUE TITLE
#trigger() method not support IE10/IE9?

### ISSUE THREAD

**Issue by gallifreyer** [eddyerburgh/avoriaz#81]
I use browser stack test IE browser. 
When I use  
`wrapper.find('.classname')[0].trigger('click')`
Get Error Message: `Object doesn't support this action`.

I want to know how to fix it?

**Comment by eddyerburgh** [comment]
I won't have time to look at this until next week, but I think it can be fixed by adding an event polyfill - https://stackoverflow.com/questions/26596123/internet-explorer-9-10-11-event-constructor-doesnt-work

If you wanted to make a PR, it would be greatly appreciated 😇

**Comment by eddyerburgh** [comment]
Sorry, shouldn't have closed.

I've added a workaround in 2.6.3 but am unable to confirm in IE.

Can you confirm the fix?

**Comment by eddyerburgh** [comment]
Are you able to test this some time?

**Comment by gallifreyer** [comment]
I've alreadty test this fix in IE. It works.
I'm sorry to test this too late. Thank you.
