### ISSUE TITLE
Changing values and triggering inputs

### ISSUE THREAD

**Issue by justincscott16** [eddyerburgh/avoriaz#84]
I am currently on `avoriaz 1.13.1` and use `simulate()` pretty regularly in my Vue Component tests as so:

```js
const component = mount(SearchForm)
const searchInput = component.find("input#search")[0]
searchInput.element.value = 'Jane Doe'
searchInput.simulate('input')
```

These specs work correctly and pass.

As I upgraded to `avoriaz 2.4.3`, and I change the deprecated `simulate()` to `trigger()`, the specs fail. I also noticed that if I console log `searchInput.element`, it will log `HTMLInputElement { _prevClass: '', _value: '' }`, and if I console log `searchInput.element.value`, it console logs nothing. Previously, console logging `searchInput.element.value` would return a value and would be set correctly. I have looked around and am wondering why when I upgrade, `searchInput.element.value` doesn't seem to be returning anything like it use to.

I am still learning a lot about Vue and avoriaz, so it is quite possible I just missed something. But was wondering if you had any ideas @eddyerburgh. Thanks for any help 😄

**Comment by eddyerburgh** [comment]
Hey, thanks for the bug report 😄 . Sorry for the late response. I've been really busy.

Would you able to write a minimal failing test? I'm going to busy for at least the next week, but should have 30mins to try and solve your issue. It would be a lot easier for me if I could copy and paste the test you were trying to run.

**Comment by justincscott16** [comment]
@eddyerburgh I am pretty busy this week too, but when I am able to get back to working on testing I will get you a minimal reproduction case! Hopefully by the end of the week!

**Comment by justincscott16** [comment]
@eddyerburgh finally got to getting back to this! Here we go, a super basic component with an input, and then the two tests, one with `trigger()` and one with `simulate()`! Also a sidenote

```javascript
// SearchForm.vue

<template>
  <div>
    <form method='get' action='some.api.endpoint' accept-charset="utf-8">
      <input id='query' v-model="searchQuery" name='query' type='search'>
      <input type='submit' value='Search'>
    </form>
  </div>
</template>

<script>
export default {
  name: 'search-form',
  data: function () {
    return {
      searchQuery: ''
    }
  }
}
</script>

// SearchForm.test.js

import Vue from 'vue'
import { expect } from 'chai'
import avoriaz, { mount } from 'avoriaz'
import SearchForm from '../path/to/SearchForm.vue'

Vue.config.productionTip = false

describe('SearchForm.vue', () => {

  // This passes
  it('changes input with simulate()', () => {
    let component = mount(SearchForm)
    const searchInput = component.find('input#query')[0]
    searchInput.element.value = 'hello'
    searchInput.simulate('input')
    expect(searchInput.element.value).to.eq('hello')
  })

  // This does not
  it('changes input with trigger()', () => {
    let component = mount(SearchForm)
    const searchInput = component.find('input#query')[0]
    searchInput.element.value = 'hello'
    searchInput.trigger('input')
    expect(searchInput.element.value).to.eq('hello')
  })
})
```

**Comment by eddyerburgh** [comment]
The problem was that I had added update inside of trigger to fix this issue - https://github.com/eddyerburgh/avoriaz/issues/66. 

I've now removed that update in the v3.0.0 . `trigger` will behave the same way as simulate. 

Note that 3.0.0 has removed `simulate`, `dispatch`, `style` and `use`.

Let me know if it fixes your issue

**Comment by justincscott16** [comment]
@eddyerburgh works great, all my specs passed with simply replacing `simulate` with `trigger`. Also, switching to `Vue.use(Vuex)` was a simple find and replace from what I had which was `avoriaz.use(Vuex)`.

Thanks for the help and the quick response and fix, you are the man, love your software!
