### ISSUE TITLE
Cannot resolve module 'avoriaz' running the latest version (2.6.3)

### ISSUE THREAD

**Issue by Dobbychen** [eddyerburgh/avoriaz#90]
I have been unit testing using Avoriaz module since I have started Vue testing, and thanks for having a nice library!

However, when I updated the module to the latest version, the `Module not found: Error: Cannot resolve module 'avoriaz` error message occurs in every spec file. ( tried in both windows and linux), and there issomebody else also encountering the same [issue](https://stackoverflow.com/questions/45267177/module-not-found-error-cant-resolve-avoriaz).

**Comment by eddyerburgh** [comment]
Hi @Dobbychen , yes I changed the way the module was exported. I tested it and thought it was working - but it's not.

I'm going to revert to the previous build for v2.6.5, and release the changed export system in a major version.

I'll update when I've reverted.

**Comment by eddyerburgh** [comment]
@Dobbychen Can you try installing latest - v.2.6.5 . It should be fixed

**Comment by Dobbychen** [comment]
@eddyerburgh Cloning the latest version from github fixes the problem!

Even though in npmjs.com it states the latest avoriaz version is 2.6.5, using npm command can still only fetch 2.6.3. How long does it normally for npmjs to update packages in their registry? :)

**Comment by eddyerburgh** [comment]
@Dobbychen it's pretty instant. Are you using yarn?

Can you try again, but remove the avoriaz line from package.json before running npm install --save-dev avoriaz?

Thanks 🙂

**Comment by Dobbychen** [comment]
+-- avoriaz@2.6.5  installed.
Big thumbs up for prompt fix! 👍 👍 👍

**Comment by eddyerburgh** [comment]
Great, thanks for the report 😄
