### ISSUE TITLE
Question: Passing props to slot components

### ISSUE THREAD

**Issue by nekosaur** [eddyerburgh/avoriaz#93]
Say I have a multi-part component where the markup looks something like this, and I need to test some interaction between the components.

```html
<parent :foo="bar">
  <child :bar="foo"></child>
  <child :bar="foo2"></child>
</parent>
```

I can mount the `parent` component with props, and I can add the children to the default slot

```javascript
const wrapper = mount(Parent, {
  propsData: {
    foo: bar
  },
  slots: {
    default: [Child, Child]
  }
}
```

But what's the best way of making sure the `child` components get created with the prop values?

**Comment by eddyerburgh** [comment]
There isn't currently a way. I can look into this in the future, but I won't be able to for at least 3 weeks (I'm going on holiday). If you want to have a look at a way to solve I would happily accept a PR 🙂
