### ISSUE TITLE
Types definition file (typescript)

### ISSUE THREAD

**Issue by Micene09** [eddyerburgh/avoriaz#94]
Hi,
Because of my project's complexity, I need to code my tests files (jest) using typescript.
Having the definition file will be great for every typescript/javascript coder (just think about Vscode javascript intelligence service or a full typescript codebase)

I hope in a fast resolution, thanks in advance.

Ps. Thank you for the great job here! Avoriaz is an amazing test library!

**Comment by eddyerburgh** [comment]
Hi @Micene09 , I've been thinking about adding this for a while.

I've added a definition file in `types/index.d.ts` in 3.1.0 🚀

I'm not a TS user, so not sure if it includes all the features you'll need. If you find anything missing, either leave an issue detailing what you need or  make a PR 🙂
