### ISSUE TITLE
this.$attrs is undefined during test.  Providing attrs to mount() causes Vue warn.

### ISSUE THREAD

**Issue by Phlow2001** [eddyerburgh/avoriaz#98]
I'm testing code that uses `this.$attrs` internally.  This is always defined during runtime, but during test it's undefined.  That seems like incorrect state for tests.

If you provide attrs to mount, like this:
```javascript
const wrapper = mount(VComponent, {
  attrs: {}
})
```

then `this.$attrs` is defined, but Vue warns:

>    console.error node_modules\vue\dist\vue.runtime.common.js:477
>      [Vue warn]: $attrs is readonly.
>
>      (found in <Root>)

Is there an easy work-around or fix for this?

**Comment by eddyerburgh** [comment]
Hi, sorry I don't think so at the moment - although I'll look into it

**Comment by daekano** [comment]
Also running into this issue. Avoriaz 2.5.0.

**Comment by eddyerburgh** [comment]
This should be fixed in v3.2.1
